### ISSUE TITLE
Submit create-folder-modal-form with enter key

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#114]
### Steps to reproduce the issue

Open create folder modal.
Fill in the folder name.
Hit enter key.

### Expected result

New folder should be created
Modal should be closed

**Comment by dneukirchen** [comment]
@kasvith will resolve this one.

**Comment by kasvith** [comment]
sure in ASAP :)

**Comment by dneukirchen** [comment]
thanks @kasvith
