### ISSUE TITLE
Media Manager cloeses immediately

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#118]
### Steps to reproduce the issue

- Go to Joomla! 4 Administrator Control Panel
- Open media manager

### Expected result
- Showing up directories and files in the media storage

### Actual result
A message box showing up `200 OK` and returning immediately to the control panel home page

### System information (as much as possible)
PHP 7 with Windows

### Additional comments
This is same as in the add article section, media manager won't come up when we want to add a image to an article.

**Comment by laoneo** [comment]
PR #116 should fix that issue. Can you please test it?

**Comment by kasvith** [comment]
I tested it and it worked. Closing the issue

**Comment by dneukirchen** [comment]
thx @kasvith
