### ISSUE TITLE
Media Manager shows a empty pane

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#121]
### Steps to reproduce the issue
- Go to admin panel
- Go to media manager

### Expected result
- A hierarchy with contents uploaded into media storage 

### Actual result
- Empty pane

**Comment by laoneo** [comment]
Can you post a acreenshot where you get the empty pane?

**Comment by kasvith** [comment]
![screenshot_131](https://cloud.githubusercontent.com/assets/13379595/24365714/7fca6c1e-1334-11e7-8d3c-2cc342a66ad6.png)

Content folder shown to the right

**Comment by dneukirchen** [comment]
Please open webdeveloper toolbar and look in console and network tab. Any errors there?

**Comment by kasvith** [comment]
yes there is
 Console Tab
> error TypeError: Cannot read property 'directories' of undefined
    at http://localhost/joomla4/media/com_media/js/mediamanager.js:9253:70
    at wrappedMutationHandler (http://localhost/joomla4/media/com_media/js/mediamanager.js:7936:5)
    at commitIterator (http://localhost/joomla4/media/com_media/js/mediamanager.js:7660:7)
    at Array.forEach (native)
    at http://localhost/joomla4/media/com_media/js/mediamanager.js:7659:11
    at Store._withCommit (http://localhost/joomla4/media/com_media/js/mediamanager.js:7747:3)
    at Store.commit (http://localhost/joomla4/media/com_media/js/mediamanager.js:7658:8)
    at boundCommit (http://localhost/joomla4/media/com_media/js/mediamanager.js:7614:19)
    at http://localhost/joomla4/media/com_media/js/mediamanager.js:9095:9

**Comment by dneukirchen** [comment]
In the network tab you should see a xhr request to our api endpoint (index.php?option=com_media...). 

Does it return a 200 OK status? Can you post the response content here?

Thanks.

**Comment by kasvith** [comment]
@dneukirchen yes there it is with HTTP 200 OK

**Comment by dneukirchen** [comment]
Can you post the response here?

**Comment by kasvith** [comment]
```{"success":true,"message":null,"messages":null,"data":[{"type":"dir","name":"a_folder","path":"C:\\xampp\\htdocs\\joomla4\\images\\a_folder","extension":"","size":0,"create_date":"2017-03-27T14:13:18+00:00","create_date_formatted":"2017-03-27 14:13:18","modified_date":"2017-03-27T14:13:18+00:00","modified_date_formatted":"2017-03-27 14:13:18","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"banners","path":"C:\\xampp\\htdocs\\joomla4\\images\\banners","extension":"","size":0,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"can","path":"C:\\xampp\\htdocs\\joomla4\\images\\can","extension":"","size":0,"create_date":"2017-03-27T14:14:29+00:00","create_date_formatted":"2017-03-27 14:14:29","modified_date":"2017-03-27T14:14:29+00:00","modified_date_formatted":"2017-03-27 14:14:29","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"ee","path":"C:\\xampp\\htdocs\\joomla4\\images\\ee","extension":"","size":0,"create_date":"2017-03-27T15:10:00+00:00","create_date_formatted":"2017-03-27 15:10:00","modified_date":"2017-03-27T15:10:00+00:00","modified_date_formatted":"2017-03-27 15:10:00","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"headers","path":"C:\\xampp\\htdocs\\joomla4\\images\\headers","extension":"","size":0,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"new","path":"C:\\xampp\\htdocs\\joomla4\\images\\new","extension":"","size":0,"create_date":"2017-03-27T14:13:50+00:00","create_date_formatted":"2017-03-27 14:13:50","modified_date":"2017-03-27T14:13:50+00:00","modified_date_formatted":"2017-03-27 14:13:50","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"r","path":"C:\\xampp\\htdocs\\joomla4\\images\\r","extension":"","size":0,"create_date":"2017-03-27T15:28:08+00:00","create_date_formatted":"2017-03-27 15:28:08","modified_date":"2017-03-27T15:28:08+00:00","modified_date_formatted":"2017-03-27 15:28:08","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"sampledata","path":"C:\\xampp\\htdocs\\joomla4\\images\\sampledata","extension":"","size":0,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"t","path":"C:\\xampp\\htdocs\\joomla4\\images\\t","extension":"","size":0,"create_date":"2017-03-27T14:12:59+00:00","create_date_formatted":"2017-03-27 14:12:59","modified_date":"2017-03-27T14:12:59+00:00","modified_date_formatted":"2017-03-27 14:12:59","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"tt","path":"C:\\xampp\\htdocs\\joomla4\\images\\tt","extension":"","size":0,"create_date":"2017-03-27T15:28:28+00:00","create_date_formatted":"2017-03-27 15:28:28","modified_date":"2017-03-27T15:28:28+00:00","modified_date_formatted":"2017-03-27 15:28:28","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"w","path":"C:\\xampp\\htdocs\\joomla4\\images\\w","extension":"","size":0,"create_date":"2017-03-27T15:28:00+00:00","create_date_formatted":"2017-03-27 15:28:00","modified_date":"2017-03-27T15:28:00+00:00","modified_date_formatted":"2017-03-27 15:28:00","mime_type":"directory","width":0,"height":0},{"type":"file","name":"index.html","path":"C:\\xampp\\htdocs\\joomla4\\images\\index.html","extension":"html","size":31,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"text\/html","width":0,"height":0},{"type":"file","name":"joomla_black.png","path":"C:\\xampp\\htdocs\\joomla4\\images\\joomla_black.png","extension":"png","size":4979,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"image\/png","width":225,"height":50},{"type":"file","name":"powered_by.png","path":"C:\\xampp\\htdocs\\joomla4\\images\\powered_by.png","extension":"png","size":3197,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"image\/png","width":294,"height":44}]}```

**Comment by kasvith** [comment]
it seems like an error in the vue component

**Comment by dneukirchen** [comment]
Ok, thank you. I have everything i need. Will look into this asap.

**Comment by dneukirchen** [comment]
Tested it locally. I cant reproduce the error. 

@kasvith 
Are you sure that you use the latest milestone1 branch?
Please also make sure, that you cleaned your cache.

**Comment by kasvith** [comment]
Yes it is the latest branch after PR #116

**Comment by laoneo** [comment]
Can be the problem with the windows file paths?

**Comment by dneukirchen** [comment]
Just a little update on this: we are able to reproduce the issue and fixing it asap. Thank you for the report @kasvith

**Comment by kasvith** [comment]
@dneukirchen whats the cause for the issue ?

**Comment by dneukirchen** [comment]
Its related to win file paths.

**Comment by kasvith** [comment]
are you guys using Macs or Linux ?
I'll develop using windows then we can track those issues too.

**Comment by dneukirchen** [comment]
allon is using linux, im using a mac currently.

**Comment by laoneo** [comment]
In the file administrator/components/com_media/libraries/media/file/adapter/local.php can you add after line 261 a `echo $this->rootPath.' '. $path;die;` statement. When you open the media manager in the back end, what's the result of the ajax request?

**Comment by N6REJ** [comment]
@laoneo Allon I get a 200

**Comment by kasvith** [comment]
@laoneo Same I also get a HTTP 200

Using Chrome Console I got for **General tab**

Request URL:http://localhost/joomla4/administrator/index.php?option=com_media&format=json&task=api.files&path=/
Request Method:GET
Status Code:200 OK
Remote Address:[::1]:80

**Response Tab**

> HTTP/1.1 200 OK
> Date: Thu, 30 Mar 2017 14:39:05 GMT
> Server: Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.1
> X-Powered-By: PHP/7.1.1
> Content-Length: 71
> Keep-Alive: timeout=5, max=99
> Connection: Keep-Alive
> Content-Type: text/html; charset=UTF-8

**Request Headers**

> GET /joomla4/administrator/index.php?option=com_media&format=json&task=api.files&path=/ HTTP/1.1
> Host: localhost
> Connection: keep-alive
> Accept: application/json, text/javascript, */*; q=0.01
> X-Requested-With: XMLHttpRequest
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
> Referer: http://localhost/joomla4/administrator/index.php?option=com_media
> Accept-Encoding: gzip, deflate, sdch, br
> Accept-Language: en-US,en;q=0.8
> Cookie: 5a8c42b16d46b5636a087870ee790c09=ej7p5aa5l92kpdmrc2qgksstqu

I navigated to above 
> http://localhost/joomla4/administrator/index.php?option=com_media&format=json&task=api.files&path=/ 

and i got following in browser 

> C:\xampp\htdocs\joomla4/images/ C:\xampp\htdocs\joomla4\images\a_folder

**Comment by laoneo** [comment]
Can you guys please test #124. Does it fix the issue?

**Comment by kasvith** [comment]
@laoneo not working yet here is the xhr response

{"success":true,"message":null,"messages":null,"data":[{"type":"dir","name":"a_folder","path":"C:\\xampp\\htdocs\\joomla4\\images\\a_folder","extension":"","size":0,"create_date":"2017-03-27T14:13:18+00:00","create_date_formatted":"2017-03-27 14:13:18","modified_date":"2017-03-27T14:13:18+00:00","modified_date_formatted":"2017-03-27 14:13:18","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"banners","path":"C:\\xampp\\htdocs\\joomla4\\images\\banners","extension":"","size":0,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"can","path":"C:\\xampp\\htdocs\\joomla4\\images\\can","extension":"","size":0,"create_date":"2017-03-27T14:14:29+00:00","create_date_formatted":"2017-03-27 14:14:29","modified_date":"2017-03-27T14:14:29+00:00","modified_date_formatted":"2017-03-27 14:14:29","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"ee","path":"C:\\xampp\\htdocs\\joomla4\\images\\ee","extension":"","size":0,"create_date":"2017-03-27T15:10:00+00:00","create_date_formatted":"2017-03-27 15:10:00","modified_date":"2017-03-27T15:10:00+00:00","modified_date_formatted":"2017-03-27 15:10:00","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"headers","path":"C:\\xampp\\htdocs\\joomla4\\images\\headers","extension":"","size":0,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"new","path":"C:\\xampp\\htdocs\\joomla4\\images\\new","extension":"","size":0,"create_date":"2017-03-27T14:13:50+00:00","create_date_formatted":"2017-03-27 14:13:50","modified_date":"2017-03-27T14:13:50+00:00","modified_date_formatted":"2017-03-27 14:13:50","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"r","path":"C:\\xampp\\htdocs\\joomla4\\images\\r","extension":"","size":0,"create_date":"2017-03-27T15:28:08+00:00","create_date_formatted":"2017-03-27 15:28:08","modified_date":"2017-03-27T15:28:08+00:00","modified_date_formatted":"2017-03-27 15:28:08","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"sampledata","path":"C:\\xampp\\htdocs\\joomla4\\images\\sampledata","extension":"","size":0,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"t","path":"C:\\xampp\\htdocs\\joomla4\\images\\t","extension":"","size":0,"create_date":"2017-03-27T14:12:59+00:00","create_date_formatted":"2017-03-27 14:12:59","modified_date":"2017-03-27T14:12:59+00:00","modified_date_formatted":"2017-03-27 14:12:59","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"tt","path":"C:\\xampp\\htdocs\\joomla4\\images\\tt","extension":"","size":0,"create_date":"2017-03-27T15:28:28+00:00","create_date_formatted":"2017-03-27 15:28:28","modified_date":"2017-03-27T15:28:28+00:00","modified_date_formatted":"2017-03-27 15:28:28","mime_type":"directory","width":0,"height":0},{"type":"dir","name":"w","path":"C:\\xampp\\htdocs\\joomla4\\images\\w","extension":"","size":0,"create_date":"2017-03-27T15:28:00+00:00","create_date_formatted":"2017-03-27 15:28:00","modified_date":"2017-03-27T15:28:00+00:00","modified_date_formatted":"2017-03-27 15:28:00","mime_type":"directory","width":0,"height":0},{"type":"file","name":"index.html","path":"C:\\xampp\\htdocs\\joomla4\\images\\index.html","extension":"html","size":31,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"text\/html","width":0,"height":0},{"type":"file","name":"joomla_black.png","path":"C:\\xampp\\htdocs\\joomla4\\images\\joomla_black.png","extension":"png","size":4979,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"image\/png","width":225,"height":50},{"type":"file","name":"powered_by.png","path":"C:\\xampp\\htdocs\\joomla4\\images\\powered_by.png","extension":"png","size":3197,"create_date":"2017-03-27T13:11:36+00:00","create_date_formatted":"2017-03-27 13:11:36","modified_date":"2017-03-20T16:43:00+00:00","modified_date_formatted":"2017-03-20 16:43:00","mime_type":"image\/png","width":294,"height":44}]}

**Comment by dgrammatiko** [comment]
@dneukirchen @laoneo from a security perspective I think is totally wrong to expose the full path to the image, it should always be the relative (to the root installation of the site). 
`"path":"C:\xampp\htdocs\joomla4\images\joomla_black.png",` this really looks bad

**Comment by laoneo** [comment]
That's what we try to fix, when you open it on linux, then only the relative path is returned.

**Comment by dneukirchen** [comment]
https://github.com/joomla/joomla-cms/pull/14139
https://github.com/joomla/joomla-cms/issues/11102

**Comment by dneukirchen** [comment]
@dgt41 fixed the full path issue with my latest changes in #125 
@kasvith can you test #125 ?

**Comment by kasvith** [comment]
@dneukirchen issue still there 

![image](https://cloud.githubusercontent.com/assets/13379595/24581339/e70096a0-1736-11e7-9ea2-dad4fe766249.png)

**Comment by kasvith** [comment]
@dneukirchen wait still its a PR right, I thought it was merged, my bad

**Comment by kasvith** [comment]
@dneukirchen @laoneo it works as excepted. thanks for the effort

![image](https://cloud.githubusercontent.com/assets/13379595/24581382/cd35d7ca-1737-11e7-9168-75f093852265.png)

**Comment by dneukirchen** [comment]
fixed. thanks you all.
