### ISSUE TITLE
Style the edit view

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/media-manager-improvement#127]
The actual edit view is very simple, despite that it needs some styling.

**Comment by dgrammatiko** [comment]
@ciar4n this one is for you

**Comment by ciar4n** [comment]
Any preference in how the edit view should be laid out?

**Comment by laoneo** [comment]
Not from my side. Let your fantasy flow :-)

**Comment by ciar4n** [comment]
That could be dangerous :-)

I'll come up with something

**Comment by kasvith** [comment]
Make it something like a basic paint

**Comment by dneukirchen** [comment]
thx @ciar4n
