### ISSUE TITLE
How to open the edit view?

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/media-manager-improvement#128]
With the current code, the edit view of an image is opened trough double click, we need here something better.

**Comment by dneukirchen** [comment]
Imo a toolbar button would be the best option here. 
Dblclick should open a preview of the file.

**Comment by kasvith** [comment]
A context menu defiantly helps in this situation. I've opened the issue #185 

User can click an image, right click on it and select **Edit image...** from there

**Comment by laoneo** [comment]
As the browser comes already with a context menu, I personally don't like web sites which do have their own context menu. But this is only my personal opinion.
What we really need to keep in mind is that the media manager should also work on touch devices as @dneukirchen already pointed out in #185.

**Comment by kasvith** [comment]
We can use both, for a PC based web browser or an iPad like tablet, it would be much better having a context menu IMO, for mobile we can load a light weight version of MM with a toolbar

**Comment by ciar4n** [comment]
Some options could be displayed on hover of the item (touch on mobile) which could include an 'Edit' option.

**Comment by ciar4n** [comment]
A solution to this was added with #201

**Comment by laoneo** [comment]
Question remains if we should support to open the edit view from the toolbar as in the rest of Joomla.

**Comment by dneukirchen** [comment]
Im in favor of the toolbar. The hover-menu is only by ui-sugar.
