### ISSUE TITLE
Enhance resize plugin

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/media-manager-improvement#134]
The resize plugin needs some improvements for the integration.

- Some input boxes for width and height.
- Better reflection of the demensions.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/18145#issuecomment-332786166

https://github.com/joomla/joomla-cms/pull/18145#issuecomment-332787017

https://github.com/joomla/joomla-cms/pull/18145#issuecomment-332791096
