### ISSUE TITLE
Fix CS errors 

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#142]
http://213.160.72.75/joomla-projects/media-manager-improvement

**Comment by zero-24** [comment]
I'm on it. I just need some time to clone the repo 😄 Give me a few minutes.

**Comment by yvesh** [comment]
Thanks @zero-24

**Comment by zero-24** [comment]
https://github.com/joomla-projects/media-manager-improvement/pull/143 @dneukirchen
