### ISSUE TITLE
Folder tree is not sorted on a new folder creation

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#144]
### Steps to reproduce the issue
- Go to media manager
- Create multiple folders

### Expected result
- A sorted folder tree

### Actual result
- Unsorted folder tree

### System information (as much as possible)
- PHP 7 Windows 10

### Additional comments
If you reloaded media manager, **folders will appear sorted**, but when creating with **Create Folder** button, new folders appends to the bottom of the tree making list unsorted

**Comment by dneukirchen** [comment]
@kasvith created PR #146 to fix this.

**Comment by kasvith** [comment]
@dneukirchen will check ASAP

**Comment by kasvith** [comment]
PR #146 fixed the issue, closing Issue
