### ISSUE TITLE
Open the list view with a path

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/media-manager-improvement#156]
As when we are editing an image and do press cancel, the list view is opened with the root path and not the folder we are editing the image from. So it should be possible to open the media manager with a path attribute.

For example an url in the back end like `/administrator/index.php?option=com_media?path=/sampledata/parks/landscape` should directly open the folder **/sampledata/parks/landscape**.

![image](https://cloud.githubusercontent.com/assets/251072/24789138/d5adbe5c-1b71-11e7-82bc-8275ac226cf1.png)

**Comment by rajikaimal** [comment]
@laoneo @dneukirchen Hey, I managed to reproduce the bug. Is anyone currently working on this ?

**Comment by dneukirchen** [comment]
No, nobody is working on it. Go ahead if you have time.
Thanks! 👍

**Comment by rajikaimal** [comment]
Sure, I'll work on this. Thanks @dneukirchen

**Comment by laoneo** [comment]
That will be a great fix!

**Comment by laoneo** [comment]
@rajikaimal did you do something on this issue? We have a code sprint next week and I want avoid that two parties are working on the same task.

**Comment by rajikaimal** [comment]
Hey @laoneo, sorry I didn't get much time to look into this as I planned. Feel free to reassign this.

**Comment by kasvith** [comment]
First we need to make sure how image editing works with Multi Adapter Architecture and then you can work on this @rajikaimal
