### ISSUE TITLE
Move local adapter to Joomla plugin

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/media-manager-improvement#159]
Actually the adapter which implements the `MediaFileAdapterInterface` is injected into the [constructor of the api model](https://github.com/joomla-projects/media-manager-improvement/blob/milestone1/administrator/components/com_media/models/api.php#L39).

To be prepared for multiple adapters in a model, the local adapter should be put into a Joomla plugin and then loaded trough Joomla events in the model.

**Comment by kasvith** [comment]
@laoneo is this plugin supposed to be used as the base plugin, for 3rd party media manager extensions ?
So they can use this for save files from clouds to local

**Comment by laoneo** [comment]
For this issue it is not relevant if the local plugin will serve as base plugin for the cloud plugins or not. This question we have to answer then when we start to implement the cloud adapters, but for now you can concentrate on the move only.

**Comment by laoneo** [comment]
Pr is merged.
