### ISSUE TITLE
Make the tree sidebar scrollable

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#169]
![bildschirmfoto 2017-04-07 um 12 33 29](https://cloud.githubusercontent.com/assets/1134007/24796735/83e4ef38-1b8e-11e7-9a13-e2dd454c3331.png)

The tree sidebar should be scrollable.

**Comment by dneukirchen** [comment]
@ciar4n probably another one for you 😳 ?

**Comment by ciar4n** [comment]
Sure... will have a look.

**Comment by ciar4n** [comment]
Fixed with #170
