### ISSUE TITLE
What should happen to long folder names in tree?

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#173]
We need to decide how we should handle long/overlapping folder names in the tree sidebar.

Possible options: 

A) Truncate them and show a tooltip on hover
B) Break them in multiple lines
C) Just truncate them
D) other options?

![bildschirmfoto 2017-04-08 um 10 54 50](https://cloud.githubusercontent.com/assets/1134007/24827439/eefa1670-1c49-11e7-95f9-dc11a3febdbe.png)

**Comment by dneukirchen** [comment]
I like the way google drive solves this with a tooltip for overlapping folder names:

![bildschirmfoto 2017-04-08 um 10 59 38](https://cloud.githubusercontent.com/assets/1134007/24827466/8192115e-1c4a-11e7-8459-34ea75b1ad03.png)

**Comment by ciar4n** [comment]
+1 for truncating with a tooltip

**Comment by Bakual** [comment]
What happens when the tree itself gets to deep? Can we scroll horizontal?

**Comment by dneukirchen** [comment]
No, currently we dont allow horizontal scrolling.  
Thats another interesting question. Imo horizontal + vertical scrolling leads to bad ux.

Here is what google does in this case 😞  (no scrolling)

![bildschirmfoto 2017-04-08 um 11 43 10](https://cloud.githubusercontent.com/assets/1134007/24827787/f34c7f40-1c50-11e7-9c92-bc01f814161b.png)

**Comment by ciar4n** [comment]
Considering excessively deep trees, the only options I can imagine available are..

- Only show the closest parent levels (eg. 3 levels up from active)
- Use a different approach for the folders altogether (eg. https://tympanus.net/Blueprints/MultiLevelMenu/)
- Horizontal scrolling (I'd agree with @dneukirchen on this)
- Option to expand width of folder tree
- Nothing with deep levels hidden

**Comment by kasvith** [comment]
+1 for option **A**

**Comment by Bakual** [comment]
In all Windows programs I know, you can scroll horizontal in this case.
While it may not be best UX in general, it is certainly better than truncating folder names or let them hide behind border (like in the Google example). In this specific case, I'd say horizontal scrolling is the best option (if it is possible, I don't know that) and what the user actually would expect.

**Comment by dneukirchen** [comment]
Has anybody an example of a tree view which solves this problem nicely?

Im still against horizontal scrolling. It is horrible in terms of UX and it does not give you a good overview of the filesystem. I agree, that hiding deeply nested folders is also bad, but if we need to show those deep nested folders in the tree view, we have to come up with something different. 

Perhaps we can make the tree sidebar column resizable, so that the user can increase the width of the tree column if he needs to. What do you think?

I took a look at 8 web media managers. None of them allows horizontal scrolling in the tree view. 2 of them (typo and elfinder) allow to resize the column.

## jce filemanager (no scrolling): 

![bildschirmfoto 2017-04-09 um 08 57 41](https://cloud.githubusercontent.com/assets/1134007/24835437/c1b5f846-1d02-11e7-9684-6b3d2e983d53.png)

## old joomla media manager (very bad)

![bildschirmfoto 2017-04-09 um 09 09 22](https://cloud.githubusercontent.com/assets/1134007/24835497/451ac2ec-1d04-11e7-83a9-d6c29349d49f.png)

## Free web file manager (no scrolling)

![bildschirmfoto 2017-04-09 um 09 11 44](https://cloud.githubusercontent.com/assets/1134007/24835516/9b82d7be-1d04-11e7-8e0a-74c83762c0a6.png)

##  ElFinder (no scrolling, but resizable columns)

![bildschirmfoto 2017-04-09 um 09 12 58](https://cloud.githubusercontent.com/assets/1134007/24835527/cd714bc0-1d04-11e7-8eb5-d0dba91a55bb.png)

## Angular file manager (no scrolling)

![bildschirmfoto 2017-04-09 um 09 17 28](https://cloud.githubusercontent.com/assets/1134007/24835548/68268298-1d05-11e7-8d19-938c7411044d.png)

## Typo 3 (no scrolling, but resizable column)

![bildschirmfoto 2017-04-09 um 09 18 46](https://cloud.githubusercontent.com/assets/1134007/24835556/98e2025e-1d05-11e7-91ba-0555896cb920.png)

## Dropbox

no tree at all

## Google drive (no scrolling)

![bildschirmfoto 2017-04-08 um 11 43 10](https://cloud.githubusercontent.com/assets/1134007/24835573/0d5c68c2-1d06-11e7-9a59-2f1f5454acd9.png)

**Comment by Bakual** [comment]
> Has anybody an example of a tree view which solves this problem nicely?

PHPStorm, Filezilla, SmartGit and many other Windows programs allow scrolling and resizing of tree views. It's likely the same for other OS.
Windows Explorer itself allows resizing but no scrolling so that at least seems to be the minimum.
If you're strictly talking about web, then I don't know. But the web isn't exactly known for good UX for such applications.

> I'm still against horizontal scrolling. It is horrible in terms of UX and it does not give you a good overview of the filesystem.

I think it's the best option you will have for this use case, along with resizing. In this case, I don't see it as bad UX at all. Truncating or hinding is no option imho as it is the worst option you can have.

> Perhaps we can make the tree sidebar column resizable, so that the user can increase the width of the tree column if he needs to. What do you think?

Allow resizing would be the minimum I think. If that is possible to do with Bootstrap/vue/whatever you're using. It is still not better than a scrollbar. Best of course is having both.

**Comment by ciar4n** [comment]
Of the two (resize or scroll) I think resizing is the better solution. If it was just horizontal scrolling I wouldn't mind so much but when there is a possibility of both horizontal and vertical scrolls, I believe from a UX perspective it would get a little frustrating when both are present. Resizing would also look better as long as we can make it apparent that the option exists.

**Comment by laoneo** [comment]
I would also go for resizing the tree but no scrolling.

**Comment by dneukirchen** [comment]
Ok, thx for all the feedback. 👍 

Lets start with **tooltips** for long folder names and the possibility to **resize the column**, if thats ok for you @Bakual? I believe this is a good compromise. It would be nice if you take a look at this once its implemented.

**Comment by Bakual** [comment]
Personally I would do both, scrolling and resizing, but only resizing will work as well.
I don't really see the point of truncating the names when we can make them visible using resize. I think it's bad UX if you have to hover over the name to see the name. :smile: 
But go ahead, we will get feedback from the users anyway ;)

**Comment by dneukirchen** [comment]
Thx. We will try and see how it goes. If it is not good enough in terms of UX, we can add horizontal scrolling later. 

Im closing this one in favor of the 2 concrete todo issues #176 and #177.

**Comment by artisandawn** [comment]
Bridge from Adobe uses a tab for Favorite Folders as a default:
![bridge-interface](https://cloud.githubusercontent.com/assets/1074734/24872411/621f876e-1deb-11e7-9266-aae262229448.jpg)

Then if you tab over to a folder tree, you can go very deep before hitting the edge:
![bridge-interface2](https://cloud.githubusercontent.com/assets/1074734/24872518/ae6474a4-1deb-11e7-84e2-9a8af8090972.jpg)

With very light padding you can go very far.

In the case of long file names, I would encourage ... with a tooltip.
In the case of folders going too deep, I like Ciaran's idea of having the ability to make the folder window wider if needed with a simple drag option.

**Comment by kasvith** [comment]
This is from **IntelliJ** and it has a nice folder tree, which is easy for navigation, @dneukirchen i think it will do the job best, it has re sizable edges and scrollbars 

![image](https://cloud.githubusercontent.com/assets/13379595/25009622/e2b1c6da-2084-11e7-888b-a49793cf345d.png)
