### ISSUE TITLE
Refactor api controller

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#178]
We are currently doing a lot of application layer stuff in the media component controller.

* Request Method routing
* General Error handling
* Handle JsonResponses

Imo this is not the responsibility of the component controller and it would be good to refactor / move this stuff.

**Comment by laoneo** [comment]
The plan here is to wait for web services and make if it. If it will get into 4.0, then we can refactor the api controller in late alpha phase of 4.0.

**Comment by dneukirchen** [comment]
thx @rdeutz 👍
