### ISSUE TITLE
500 internal server error while uploading a GIF file

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#179]
### Steps to reproduce the issue
- Go to media manager
- Click upload button
- Select a gif file
- Upload

### Expected result
- If **gif** extension is not supported, an error message saying about it

### Actual result
- 500 Internal server error message 
- Return to the admin control panel

### System information (as much as possible)
- PHP 7 with Windows 10

**Comment by charithsoori** [comment]
works macOS Sierra with PHP 7. Someone, please verify on Windows 10.

**Comment by kasvith** [comment]
Did you reproduce the error?

**Comment by laoneo** [comment]
It works with the latest code on the milestone 1 branch, so closing it.
