### ISSUE TITLE
No root folder navigation in side bar

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#180]
### Steps to reproduce the issue
- Go to Media Manager
- Go to some sub folder

### Expected result
- A sidebar with root folder navigation

### Actual result
- No root folder in the list

### System information (as much as possible)
- PHP 7 with Windows 10 host

### Additional comments
- Yes users will put files in root folder and will go to others too, once they need to go back to root again, they'll have to refresh the page. No one likes it

**Comment by kasvith** [comment]
**No way to go back to root**

![image](https://cloud.githubusercontent.com/assets/13379595/24943736/9d32008a-1f75-11e7-9b19-851d346dd310.png)

**Comment by laoneo** [comment]
There is one here 
![image](https://cloud.githubusercontent.com/assets/251072/24951004/32661112-1f73-11e7-956d-a36bb9bd9a9a.png)

**Comment by kasvith** [comment]
seems my repo is older
