### ISSUE TITLE
Addition of Yarn support with lockfiles

### ISSUE THREAD

**Issue by rajikaimal** [joomla-projects/media-manager-improvement#181]
_Since it's not a bug, I've omitted the standard issue template_ :gear: 

Addition of support to Yarn package manager by adding a `lockfile` to manage the dependency list. Yarn uses the `lockfile` to manage consistent installations in different systems. 

[Yarn.lock](https://yarnpkg.com/en/docs/yarn-lock)

**Comment by dneukirchen** [comment]
👍  

@dgt41 do you have any objections?

**Comment by rajikaimal** [comment]
I can help with this, if you want go ahead :smile:

**Comment by dgrammatiko** [comment]
Nope, go ahead!

**Comment by rajikaimal** [comment]
I'll add a PR.

**Comment by zero-24** [comment]
@rajikaimal you can close this Issue as you have opend  your PR 😄 Thanks!

**Comment by rajikaimal** [comment]
Sure !

**Comment by laoneo** [comment]
@zero-24 in this project we have a slightly different process. We close the issue when it is actually solved and not when there is a pr available as in core.

**Comment by dneukirchen** [comment]
thanks @rajikaimal 
#187
