### ISSUE TITLE
File/Folder Copy, Move support in the local adapter

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#186]
It would be nice to implement the File/Folder 

- Copy
- Move
- Rename

functionalities in the backend local adapter, so frontend developers can use them to make basic file operations work

**Comment by kasvith** [comment]
# Directory copy/move when a directory with same name exists on the destination

## Solution 01
In this scenario we can decide to copy non existing files individually first to the existing directory
**If there are files with same name on the target directory too** user may want to **overwrite** or **skip** these files.

For that frontend should know what files are being overwritten

For overcome this, we can put all files that are about to be overwritten in a queue and send it to the frontend, so user can decide each file and backend can process files with given information

## Solution 02
In the same scenario, instead of sending the *copy, move, rename* operations directly to the adapter, front end can check for availability, if files with same name exists on the destination dir, frontend can warn the user and if he wants to overwrite them, he can do it in frontend, then a request sent to the backend with a **force** condition, if **force** is **true** backend will simply overwrite any file silently.

This requires to load the folder structure inside the filesystem when frontend loads, so analysis can be done in frontend and final action could be taken at the backend

Any comments @laoneo @dneukirchen @dgt41

**Comment by laoneo** [comment]
I would go for solution 2 as the api should not become stateful to manage some queue for the next request from the client. This is better managed in the client.

**Comment by kasvith** [comment]
And also it is easy for implement, less load on the backend

**Comment by dgrammatiko** [comment]
Could we utilise promises on the client side and adjust the backend for that?
The code will be much simpler...

**Comment by kasvith** [comment]
Can you give an example for that

**Comment by dgrammatiko** [comment]
Create folder (as xhr) returns promise, if ok folder created else the folder exists and an alert is thrown with the ability to rename, overwrite or cancel

**Comment by kasvith** [comment]
Yes we can do as you said for the frontend, in here i was bit focused on backend
For backend functions will return a **true** on **success**, will throw exceptions at any failure

**Comment by kasvith** [comment]
# Mechanism for file/folder Copy/Move

- Check if the target directory of file **exists**. 
  - If it does not exists, use the provided method on adapter to copy/move. If it is a folder, all the contents will be copied to the target directory. If it is a file target will have a copy of file.

- If it exists, we need to handover control to the user, whether files with identical names overwrite or skipped(Folder merging)
  - If this is a file, do a simple request to backend with *force* condition.
  - If this is a directory things will be little bit complex.
    - Directory is already there, so we need to do a simple query and detect all non existing files in the destination, and send a single xhr to backend with an array of non existing files, they will be copied 1st
    - Then for duplicate names, prompt user whether he wish to overwrite each file, with an *option* to **Do same for others**, so he can decide one by one, or make same decision for future prompts in the list.
       - If he selected **Do same for others**, simply send the rest of the array to the backend
       - If he selects and decide one by one, send xhr to server after each prompt saying whether files need to be overwritten or not

## **Applies for move also**

any comments on this one ?

**Comment by kasvith** [comment]
Opened PR at #188

**Comment by kasvith** [comment]
PR #188 was merged, closing issue

@laoneo @dneukirchen thanks for reviews

**Comment by kasvith** [comment]
PR #188 was merged, closing issue

@laoneo @dneukirchen thanks for reviews

**Comment by laoneo** [comment]
Actually the issue is not closed because of pr #200.

**Comment by kasvith** [comment]
Issue is closed due to pr #200
