### ISSUE TITLE
Prepare for multiple adapters

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/media-manager-improvement#190]
As with the move to a plugin based approach to load the file adapters #183. We need to support multiple filesystems. This would mean that we can have more then one root nodes.

A possible directory structure for the client can then look like:
```
- Local
- Foo Filesystem plugin
- Bar Filesystem plugin
```

The api controller will not return the folders and files below images as top level elements, instead of a node for every plugin.

**Comment by kasvith** [comment]
What would be the location of file systems?

For example, where does the *Bar* obtain files ?

**Comment by laoneo** [comment]
Foo and Bar are demo names for other filesystem plugins.

**Comment by dneukirchen** [comment]
Like Google Drive, Amazon S3 and Dropbox...

**Comment by kasvith** [comment]
at this phase we will create some mock folders as a fake roots

**Comment by kasvith** [comment]
@dneukirchen shouldn't we update our current Media Manger implementation to return a root folder ? in current version we directly see the folder tree of local file system. we cant to add a root folder to it.

Then we can easily move to multiple filesystems in the adapter.
This requires both backend and frontend modifications

**Comment by dneukirchen** [comment]
Yes.

**Comment by kasvith** [comment]
> The api controller will not return the folders and files below images as top level elements

What you meant by this @laoneo

**Comment by laoneo** [comment]
That every adapter will act as top level element.

**Comment by kasvith** [comment]
Multiple methods to overcome issue is added here

https://docs.google.com/document/d/1s_hpglTiMS1yIK8xVEXtJ2HnmmwxLGw2OaKRychJ78k/edit?usp=sharing

**Comment by laoneo** [comment]
Closing it as we have plugin based filesystem implementation with unlimited account support.

**Comment by kasvith** [comment]
Yahoo
