### ISSUE TITLE
FileSystem do not repond after long time of inactivity

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#191]
### Steps to reproduce the issue
- Go to **Media Manager**
- Keep open your tab some time(until session expires you need to stay)
- Try to open some folder in MM

### Expected result
- Folder should open or it should immediately redirect to Login page to authorize new session

### Actual result
- Nothing happens due to session expiration 

### System information (as much as possible)
- PHP 7, Windows 10

**Comment by dneukirchen** [comment]
This is not a problem of the new media manager. Its a problem of the session cookie in joomla 4 and the keep alive script. I already fixed the keep alive script in https://github.com/joomla/joomla-cms/pull/15121 (will be updated with the next upstream sync) and created an issue for the session cookie https://github.com/joomla/joomla-cms/issues/15131
