### ISSUE TITLE
Handle deactivated local plugin

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/media-manager-improvement#196]
When the local filesystem plugin is deactivated the following error shows up in the developer console:
![image](https://cloud.githubusercontent.com/assets/251072/25379315/ec180e1a-29ac-11e7-8930-dc61ad24835e.png)

### Steps to reproduce the issue
- Deactivate the local plugin in the filesystem group.
- Open the media manager in the back end.

### Expected result
No error in the developer console.

### Actual result
Error in the developer console as shown in the description.

### System information (as much as possible)
Media Manager repo.

**Comment by kasvith** [comment]
Checkout PR #202
