### ISSUE TITLE
Thumbnails and croping features ?

### ISSUE THREAD

**Issue by pulsarinformatique** [joomla-projects/media-manager-improvement#21]
Hi

Will this new mediamanager allow us to upload a large image and create as many thumbnails we need with a JS croping interface ?

thanks

cyril

**Comment by jissereitsma** [comment]
Yes, this is one of the scopes and it might be included in exactly the way as you need it. However, we will be unable to give any guarantees on the progress we make from within these specific project pages. Guarantees are only given by the Joomla Project once a feature is written and included in the Joomla core. As of yet, all of the work in this project is voluntary, so the best way to guarantee features is to join this voluntary team ;)

**Comment by pulsarinformatique** [comment]
Ok , I can help but only on a test / doc level

**Comment by jissereitsma** [comment]
Thanks. I'll write you down in the wiki for that. For now, we are focussing only on hard-core development so for now things will be quiet.
