### ISSUE TITLE
Foldertree parent indicator needed

### ISSUE THREAD

**Issue by ciar4n** [joomla-projects/media-manager-improvement#216]
Indicator needed for folders in foldertree if sub folders exist. Possibly a + symbol aligned to the right of the folder name.

**Comment by laoneo** [comment]
Can you post a screenshot where exactly you need it.

**Comment by dneukirchen** [comment]
It requires additional data from api response OR additional XHR requests. As discussed with @ciar4n  some weeks ago, im against this feature because of cost-benefit considerations.

**Comment by laoneo** [comment]
I second this, probably something we can look again when we have the cloud file system integration. If we can do it without overflowing the server with requests, it can be considered.

**Comment by ciar4n** [comment]
Close for now?

**Comment by laoneo** [comment]
I would leave it open, just with the remark that we look later into it. I put it on milestone 2.

**Comment by kasvith** [comment]
Won't this be useful when multiple file systems are presented  ?

**Comment by laoneo** [comment]
Because of performance reasons it doesn't make sense to have this feature implemented for the value you gain. So closing it.
