### ISSUE TITLE
Remove download button from hover-tools

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#225]
The feature is nice, but imo the download will not be used very often. We should remove it from the hover-tools and move the action button to the joomla-toolbar or some other place (infobar or app-toolbar?).

![bildschirmfoto 2017-05-19 um 06 55 18](https://cloud.githubusercontent.com/assets/1134007/26233788/25efbf8c-3c60-11e7-85a4-336ec651cb18.png)

What do you think?

Joomla 4 definitely needs a good concept for all those action buttons. Is anybody working on that atm?

**Comment by ciar4n** [comment]
The media manager is unique in that it is the only view with items displayed in a grid. So I think it is safe for us to set the precedent regarding how such actions are displayed.

For tables/lists there is https://github.com/joomla/joomla-cms/pull/16076 where primary inline actions are displayed as icons and secondary actions displayed in a dropdown..

![media-actions](https://cloud.githubusercontent.com/assets/2803503/26237148/ca307f9a-3c6b-11e7-998c-3b89dc66b4a3.png)

I agree that 'download' could be removed in this case.

**Comment by dneukirchen** [comment]
thx @ciar4n
