### ISSUE TITLE
UX feedback

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#228]
# German FB group, video preview 23.05.17

![mm-demo](https://cloud.githubusercontent.com/assets/1134007/26402697/9dfc18e8-408b-11e7-95c2-a700ca754277.gif)

### Feedback:

* ~~~Make the thumbnails in the listview resizeable~~~
* ~~~Drag&Drop!!!~~~ thx @dgt41 ❤️ 
* ~~~Force override on upload, move, rename~~~
* ~~~Presets for article images~~~
* Input fields for edit-plugin controls (especially resize plugin)
* ACL
* ~~~Using it in Frontend~~~

**Comment by dgrammatiko** [comment]
> Presets for article images

What do they mean with this?
Actually whatever they mean I disagree, **all** images should implement `srcset` so in that sense a predefined preset is useless...

**Comment by dneukirchen** [comment]
Some users want to define presets for the article image upload. i.e.: every image_large that i upload should automatically be resized to 700px width. 

In the early stages of the new media manager we talked a lot about features like this and we should keep them in mind for milestone 2 or 3.

**Comment by dneukirchen** [comment]
@laoneo can you add some feedback you got from the jab presentation? thx

**Comment by laoneo** [comment]
- Most people do miss support for stuff like automatic thumbnail generation in combination with source sets.
- To open the same folder where it was left last time, see issue #246.
- More compact view for the media form field.

**Comment by dneukirchen** [comment]
I will close this one. Most of the requested features/improvements is already implemented and we have already created issues for the rest.
