### ISSUE TITLE
Filenames with spaces cause 403

### ISSUE THREAD

**Issue by dgrammatiko** [joomla-projects/media-manager-improvement#230]
### Steps to reproduce the issue

Try to upload a file that the filename contains a space

### Expected result

Uploads normally 

### Actual result

Error 403 on ok exits app!

**Comment by dneukirchen** [comment]
@laoneo can you take a look at this? seems to be server related.

**Comment by laoneo** [comment]
Somebody at JAB fixed it, so waiting for the pull request.

**Comment by dneukirchen** [comment]
perfect, thx

**Comment by ylahav** [comment]
It seems to me that the PR #261 and #262 can be accepted.
BTW - Can I run the tests for code convention (or any other test) before requesting a PR?

**Comment by laoneo** [comment]
Yes, do a `composer install` in the Joomla root dir. Then do `libraries/vendor/bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla .`

**Comment by laoneo** [comment]
Closing as the pr's got merged.
