### ISSUE TITLE
We have to figure out what we're going to do with the xtd-image

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#239]
see #236 

@dgt41 any suggestions?

**Comment by dneukirchen** [comment]
As discussed in the last status meeting, we will add an url param to let the client app know when it is in selection mode (opened by a formfield or xtd button). Then we can add insert options like alt-text, class-name... and probably modifiy the layout to gain more space. This is similar to the way the old media manager handled it. 

We postpone this to ms2

**Comment by laoneo** [comment]
Is this issue still valid as the xtd button got refactored at the last code sprint in Frankfurth?

**Comment by laoneo** [comment]
Closing this in favor of #530.
