### ISSUE TITLE
Image filename issue on <a> and <img> tags

### ISSUE THREAD

**Issue by ciar4n** [joomla-projects/media-manager-improvement#24]
Probably just another example of my ignorance on the backend of this project however I am having the following issue within the Media Manager..

![media-manager1](https://cloud.githubusercontent.com/assets/2803503/18229634/a30f8e00-7278-11e6-8a36-7055e4f590c7.jpg)

It appears the image filename within the **a** and **img** tags is including the entire local path rather than just the filename resulting in both been inaccessible..

```
<img width="60" height="13" alt="joomla_black.png - 4.86 kb" src="http://localhost/media-manager-improvement/images/C:\xampp\htdocs\media-manager-improvement\images\joomla_black.png">
```

```
<a class="img-preview" title="joomla_black.png" href="index.php?option=com_media&view=file&file=C:\xampp\htdocs\media-manager-improvement\images\joomla_black.png">
```
#### Steps to reproduce the issue

Open the Media Manager
#### System information (as much as possible)

Running on a localhost with the latest version of XAMPP
PHP Version: 5.6.24
Database Version: 5.5.5-10.1.16-MariaDB 
Safe Mode: Off
Open basedir: None
Display Errors: On
Short Open Tags: Off
File Uploads: On
Magic Quotes: Off
Register Globals: Off
Output Buffering: On
Session Save Path: C:\xampp\tmp
Session Auto Start: 0
XML Enabled: Yes
Zlib Enabled: Yes

**Comment by jissereitsma** [comment]
Could you let us know also the type of PHP handler you are using under Windows? Because this is not a generic issue, but an issue specifically with Windows: Are you using `mod_php`, some kind of CGI thing or PHP-FPM?

**Comment by ciar4n** [comment]
@jissereitsma PHP info of our localhost has been made available at the following... http://ciar4n.com/phpinfo/

**Comment by jissereitsma** [comment]
Thanks. Out of security reasons I would recommend to remove the file again. Noted is now that this XAMPP runs the Apache 2.0 Handler. Perhaps somebody can pick this up for testing later on. I'm not a Windows user myself.

**Comment by ciar4n** [comment]
Thank you @jissereitsma Done.

**Comment by laoneo** [comment]
Closing this issue as part of a repository cleanup for milestone 1 https://github.com/joomla-projects/media-manager-improvement/wiki. If you still think this issue exists on milestone 1, don't hesitate to reopen it.
Thanks for understanding.
