### ISSUE TITLE
Reopen on last visited path

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/media-manager-improvement#246]
Would be nice when the Media Manager would open the last visited folder. For example when I want to select an image from a folder in article A and then open article B, it would be nice when the media manager opens the same folder initially when I want to select an image in article B.

If a form field has a hard coded directory specified, then it will only open the last opened folder when it is below that specified folder in the form field.

**Comment by dneukirchen** [comment]
Is this a ms1 feature? I know it is important for many users, but we have a lot of stuff to do in ms1. 

This feature is combined with url-state and form field overrides not as simple as it might sound and we need to clear some things out. 

Lets start with a pretty basic questions: 

1) Where to store the state?

    a) server side: session
    b) client side httpOnly cookie
    c) client side js cookie (xss)
    d) browser storage (local or session) (xss)
    f) spaceship

2) Should the state be shared across frontend and backend? Imo, no.

3) Should form-field state override component state? i.e:
    * User visits mm and navigates to `/foo/bar`
    * User opens com_3dp opens form field with hardcoded directory `/avatars`
    * User visits mm and will be presented with contents of `/avatars`

4) The url state (i.e. open media manager with path=/my/sub/folder) should override the session state. We have to implement this feature and deep linking feature first. 

5) should the path state persist across session? Ie When you logout or close browser? This is related to 1)

**Comment by dgrammatiko** [comment]
We can use storageSession here. The code is related to the media field script.
