### ISSUE TITLE
Compatiblility with IE11

### ISSUE THREAD

**Issue by Bakual** [joomla-projects/media-manager-improvement#247]
### Steps to reproduce the issue
Visit MM with IE11 (on Win7 if that matters)

### Expected result
Working Media Manager

### Actual result
![image](https://user-images.githubusercontent.com/1018684/27036734-16584542-4f86-11e7-9f47-ad1ee09bc201.png)

Console shows error
[vuex] vuex requires a Promise polyfill in this browser.
![image](https://user-images.githubusercontent.com/1018684/27036785-433ee570-4f86-11e7-9241-20ed0d2bc28b.png)

### System information (as much as possible)
IE11 on Windows 7 using XAMPP
MediaManager with state from Core.

**Comment by wilsonge** [comment]
It does. We're supporting IE11+ in J4

**Comment by kasvith** [comment]
Solution seems to be in this thread, upgrading promise

https://github.com/vuejs/vue-hackernews-2.0/issues/79

**Comment by dneukirchen** [comment]
Yes, its an easy fix. Thx for reporting.

**Comment by laoneo** [comment]
@Bakual can you please test #250 if it solves your issue?

**Comment by Bakual** [comment]
Not yet, but it's the right direction :+1:

**Comment by dneukirchen** [comment]
fixed in #250
