### ISSUE TITLE
Cropper increases filesize

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/media-manager-improvement#254]
I'm trying to get an impression of the new media manager and do some tests.

I noted one thing that might be good to be aware of. I'm not 100% sure but think file and data sizes might give some funny results when transferred with AJAX. (to Api.php)

    if ($serverlength > ($params->get('upload_maxsize', 0) * 1024 * 1024)
        || $serverlength > $helper->toBytes(ini_get('upload_max_filesize'))
        || $serverlength > $helper->toBytes(ini_get('post_max_size'))
        || $serverlength > $helper->toBytes(ini_get('memory_limit')))
    {
    ...
    // @todo find a better way to check the input, by not writing the file to the disk

My guess is that the php.ini checks will pass as the limits probably are larger. The check against the parameter can be a problem. As I understand, base64 encoded strings can be much larger than the original. I made a quick test and got 30%-40%. 

Maybe the check should be against the decoded $mediaContent string.

Another thing is the data compression. 
I uploaded a jpg file **115 kb**, 1600x1200px.
I cropped this image to 1108x805px with a filesize of **679 kb** =>  **6x LARGER**
My guess is that my original file is well compressed and the result after cropping is uncompressed.

The result has to be compressed before saving it on the server. Parameter settings for jpg and png needed.

**Comment by zero-24** [comment]
What about using the Joomla API for that: 
```php
<?php $cMax    = (int) $this->config->get('upload_maxsize'); ?>
<?php $maxSize = JUtility::getMaxUploadSize($cMax . 'MB'); ?>
<?php echo JText::sprintf('JGLOBAL_MAXIMUM_UPLOAD_SIZE_LIMIT', JHtml::_('number.bytes', $maxSize)); ?>
```

**Comment by mbabker** [comment]
Using that method won't help matters any.  Just from this code snippet, it looks like the request length is being checked against the upload limits.  It uses different logic since it looks like the actual file isn't being transferred but an alternative representation of its contents (base64 encoded string).  So the file's being read out of `$_POST` versus `$_FILES` which is treated differently in PHP.

**Comment by schnuti** [comment]
Exactly, the base64 encoded image comes via the AJAX post call in $_POST and not $_FILES. I think I understand the writers intention to have the same restrictions to maximum as a file upload. As I said, this might be a problem. (You may have used or seen base64 encoded images in css files with the url statement.)

I made a new test with the image file above. As there is no input for the size (yet?) I could not repeat the same cropping. I now also checked the intermediate sizes.
If I set the component parameter to file size max 1 MB this would fail.

- Uploaded a jpg file 1600x1200px, 115 kb
- Cropped this image to 1340x919px
- intermediate base64 size  => 1.4 MB
- intermediate decoded => 1.05MB
- saved as 1340x919px, 1.05MB

- loaded the result file into Gimp and saved (exported) it with Jpeg-Quality 80% => 146kb 

I think PHP (Joomlas Image class) gets almost the same size result after compression with quality 80%. You of course get better results from some of the online services.

**Comment by schnuti** [comment]
If the client side image editor creates that kind of "BIG" data, a direct upload to the cloud would need some kind of image compress service. Well, that's for much later milestones.

**Comment by dneukirchen** [comment]
@schnuti  thx for testing and your very valuable input. 
We will set the focus on those issues in our next steps.

**Comment by laoneo** [comment]
Thanks for reporting. Do we suffer from these issues in the cropper.js library which we are using? 
- https://github.com/fengyuanchen/cropper/issues/542
- https://github.com/fengyuanchen/cropper/issues/596.

**Comment by schnuti** [comment]
I found a method that's probably better. canvas.toBlob() and reported this on the fenguanchen project.

I'll test an alternative I found on gitHub. I've bin looking for a simple light-weight client side image editor for a long time. As is, I have to crop and resize every single image in e.g. Gimp before I can upload them to Joomla.

I'll try to edit the image in a first step **before** uploading it.

See [blueimp/JavaScript-Load-Image](https://blueimp.github.io/JavaScript-Load-Image/)

Occasionally I've used the elFinder file manager but that did not support my "workflow" any better.

**Comment by dgrammatiko** [comment]
Proposal: let's use this: https://github.com/xkeshi/image-compressor

**Comment by schnuti** [comment]
@dgt41 
First looks great. But - 

>The quality of the output image. It must be a number between 0 and 1. Be careful to use 1 as it may make the size of the output image become larger. Check out canvas.toBlob for more detail. 
>Note: This option only available for image/jpeg and image/webp images.

Problem? Seems that PNG files are not compressed. Personally I can live with it.

👍  The example is using formData.file to send the file with XMLHttpRequest (AJAX). i.e. 1: no extra 30-40 % size during upload because of a base64 encoding. 2: I have a feeling that using the "normal" file upload is a bit more secure e.g. using the system path for saving the temporary file before validating it.

**Comment by dgrammatiko** [comment]
@schnuti there was an architecture decision to use base64 against normal PHP file upload. I don't think that this could be undone at this point

**Comment by schnuti** [comment]
@dgt41 "Normal PHP file upload"? I wouldn't say that an AJAX file upload is the "normal" way. I guess it wasn't (isn't?) known how to send image-data as file-data instead of base64 encoded. 

I also believe it's easier to use HTMLCanvasElement.toBlob() directly instead of  the helper xkeshi/image-compressor. Sizing & Co is included in the Cropper utility and not needed twice.
See: [MDN - HTMLCanvasElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob)

**Comment by dgrammatiko** [comment]
@schnuti check that MDN link for the browsers support...

**Comment by schnuti** [comment]
@dgt41 check what your proposal is referencing. - The same MDN-link.

> A simple JavaScript image compressor. Uses the Browser's native canvas.toBlob API to do the compression work. General use this to precompress a client image file before upload it.

IE10+ might be a problem --- in any case.

**Comment by laoneo** [comment]
We fixed it with an additionaly quality parameter in #376.
