### ISSUE TITLE
Proposal: include an aftersave plug in - create thumbs

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/media-manager-improvement#255]
I think this is a basic need. The Media Manager should use thumbs **if available** and not original files. Did you scroll through a few hundred images with the old Media Manager? 3.d party developers can then code some more advanced plug ins. Personally I use 4 sizes of the same image.

**Comment by kasvith** [comment]
This question will be addressed in file serving. Will give you feedback

**Comment by laoneo** [comment]
As we have many feedback that some thumbnail support should be built into MM, we will target this kind of feature requests for milestone 3.

**Comment by AFlorencia** [comment]
I wonder if this thumbnails will be available in frontend, since we need to display small images in modules like mod_articles_category.
I was asking for this here: https://github.com/joomla/joomla-cms/issues/17446

**Comment by kasvith** [comment]
we can generate thumbnails based on many predefined sizes

**Comment by schnuti** [comment]
Covered in other issues.
