### ISSUE TITLE
Resize input box

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/media-manager-improvement#256]
Would be nice to have a width and height input box for the resize plugin.
![image](https://user-images.githubusercontent.com/251072/27192625-65432848-51fc-11e7-9a60-6bcc1947d1d5.png)

**Comment by schnuti** [comment]
Don't you need manual input for all? You mostly know the exact values you want to use.
Crop: x, y, width, height
Resize: width, height
Rotate: degrees 

Edit: Crop has fields but only shows the values - no action (for now?) I also see some funny green icons.

A forth setting for Aspect ratio is needed: If you want to reset the aspect ratio to "No ratio used".

**Comment by laoneo** [comment]
Yes, but we go step by step in this project. It is easier for people who want to chime in when there are small tasks.

**Comment by ciar4n** [comment]
I think some kind of stepper would work. Ideally something like...

![stepper](https://user-images.githubusercontent.com/2803503/27516164-3c8e80a2-59ac-11e7-9eab-a2d0e71f3b70.png)

It would mean improving on.. https://docs.joomla.org/Number_form_field_type

**Comment by laoneo** [comment]
Sounds like a good idea. Another nice goodie would be to have a "Keep Ratio" checkbox.

**Comment by schnuti** [comment]
I don't think you need any special form fields. The number field do well I think. The trick is that those fields have to link back to the "mouse area".
An example: The crop area is first chosen with the mouse and then corrected by entering the "exact values", not using the steps. I would enter 500 and 300 directly, if that is what I want.
You can also see the different ratio settings possible for cropping.

In other cases you can combine a range field (slider) with a number field. The slider is the quick and the number is the exact setting. Example below for an opacity setting field.

![crop-fields](https://user-images.githubusercontent.com/956537/33795926-cccf3438-dcea-11e7-98fc-169125c8275f.png)

![slider-number](https://user-images.githubusercontent.com/956537/33795929-dc0260b0-dcea-11e7-9cc3-2f7f0884bf39.png)

**Comment by laoneo** [comment]
With the pr #481 we introduced input boxes and a slider
![image](https://user-images.githubusercontent.com/251072/34101134-fbeee294-e3e4-11e7-8e66-b78b08736c8a.png)
