### ISSUE TITLE
Refactor filesystem plugin system

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#258]
Currently we are triggering onFileSystemGetAdapters in the [Api Model](https://github.com/joomla-projects/media-manager-improvement/blob/milestone1/administrator/components/com_media/Model/Api.php#L54) and use the returned values to work with the activated filesystem plugins. 

Imo the code should not depend on the return value of a plugin event. Plugin events should not return anything. You dont know what you will get. Thats how it is and how we should use it. 

So my suggestion is to create a higher level registry (we can put it in the media manager component at the beginning) and register the activated plugins when a certain plugin event is triggered. 

Then in the media manager component you only work with the registry and not with the result of the plugin event. 

In the  register method of the registry we can also check if the adapter implements the adapter interface. Thats an additional benefit.

**Comment by kasvith** [comment]
how should we get the adapter's instance to top level registry ?

**Comment by dneukirchen** [comment]
In the plugin you register the adapter instance to the registry.

I.e. send the registry instance along with the event and in the listener you simply call `$registryInstance->register('someKey', $adapter);`

**Comment by laoneo** [comment]
I guess we have to do this in milestone 1, otherwise we will have a BC break when we change to this method.

**Comment by kasvith** [comment]
Done in #300
