### ISSUE TITLE
Create new folder does not work after multi adapters

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#265]
### Steps to reproduce the issue
- Go to MM (in gsoc17 branch)
- Try to create a new folder

### Expected result
- Popup Create Folder Dialog

### Actual result
- No dialog popup

### Additional comments
Guess it needs some adjustments to use disks

**Comment by kasvith** [comment]
Issue is closed due to #268 was merged into **gsoc17** branch

**Comment by laoneo** [comment]
Does this issue only happen on the gsoc17 branch?

**Comment by kasvith** [comment]
yes, @dneukirchen did some modifications to vue
