### ISSUE TITLE
Tree view needs more styling

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#270]
Currently multi adapter architecture is implemented for Media Manager

New folder tree needs more CSS styling to make it awesome for users. As you can see in the picture there are some CSS issues.

![image](https://user-images.githubusercontent.com/13379595/28054189-9c8ec96c-6631-11e7-9091-643ca0cefe6f.png)

Also it would be nice if we could add an icon for each adapter. It can be provided by the third party developer or we can set it to default if nothing provided. An icon like this perhaps

![image](https://user-images.githubusercontent.com/13379595/28054355-21a0559e-6632-11e7-8c41-1a775edd1230.png)

**Comment by kasvith** [comment]
#282 needs styling

**Comment by dneukirchen** [comment]
done in #296 
thx @ciar4n
