### ISSUE TITLE
Download Files via Media Manager

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#277]
It would be nice if an user wanted to download a file uploaded in Media Manager to the device he uses.

This typically help users who has deleted original files

**Comment by laoneo** [comment]
Sounds for a nice idea.

**Comment by kasvith** [comment]
I badly wanted this xD

**Comment by kasvith** [comment]
Simple workaround for this is to add an option to provide a *getTemporaryLink* in the API. Most of the cloud adapters provide a functionality to get the file via a url which expires after some time, we can use that to download the file.

It needs the client support too

**Comment by kasvith** [comment]
Server side is done in #330
