### ISSUE TITLE
Media Field should be redesigned to work with Cloud Adapters

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#289]
Media Manager was updated with Cloud Filesystem integration. So now Mediafield need to be adjusted to work with latest changes.

MediaManager has an API call for this to get an sharable url for a media. This is done by sending a special AJAX request to the Media Manager like 

**[host]/administrator/index.php?option=com_media&format=json&task=api.files&url=true&path=local-0:/joomla_black.png**

Then API will provide a json respone like this

`{
	success: true,
	message: null,
	messages: null,
	data: [
	{
		type: "file",
		name: "joomla_black.png",
		path: "local-0:/joomla_black.png",
		extension: "png",
		size: 4979,
		mime_type: "image/png",
		width: 225,
		height: 50,
		create_date: "2017-08-26T17:41:48+00:00",
		create_date_formatted: "2017-08-26 17:41",
		modified_date: "2017-08-26T17:41:48+00:00",
		modified_date_formatted: "2017-08-26 17:41",
		thumb_path: "http://localhost/media-manager-improvement/images/joomla_black.png",
		url: "http://localhost/media-manager-improvement/images/joomla_black.png"
	}
	]
}`

In here url is a sharable resolved url to actual content and can be used to serve a file.

Now mediafield should be fixed to use this notation. Sending the AJAX for get the resolved URL to the media file.

@dgt41 I would say we would try to show user the unresolved path to the user in a nice way. local-0 has a name assigned and we can show it along with the disk and the relative path to user.

Actual url for the content is keep hidden in mediafield for a nice user experience.

**Comment by kasvith** [comment]
@dneukirchen is there any suggestion from you

**Comment by dneukirchen** [comment]
@dgt41 can we close this?

**Comment by ggppdk** [comment]
I am a little confused
so this was implemented  / finished ?
https://community.joomla.org/gsoc-2017/gsoc-2017-cloud-file-systems-for-joomla.html

**Comment by kasvith** [comment]
It was implemented and merged
