### ISSUE TITLE
Media Editing should be need to work with clouds

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#294]
With the introduction with the Cloud Architecture for Joomla! we now need to fix Image editing to be work with any possible adapter. 

Currently Media Manager serve the file to be edited to the Editor Plugin and it goes usual. But unfortunately due to internal Url structure of Adapter API now this simple task is not working anymore.

We need to unify how image editing from adapters **(Not only clouds)** to a single workaround.

Two possible suggestions

1. Cache media from adapter to a Local Cache folder and provide it to editor plugin to start editing, and when saving update the respective file

- Pros
  - Small code change in the backend
  
- Cons
  - Waste of bandwidth and time
  - Will be slower than usual process

2. Directly download media from adapters to Local Machine via JS and after editing, upload the respecting file to the adapter from local machine

- Pros
  - Faster
  - Simpler to process
  - No cache required

- Cons
 - Small changes to be made for both frontend and backend

**Comment by laoneo** [comment]
Closing as #550 got merged.
