### ISSUE TITLE
No thumbnail if space in filename

### ISSUE THREAD

**Issue by ciar4n** [joomla-projects/media-manager-improvement#338]
### Steps to reproduce the issue
If there is a space in an image filename, no thumbnail is displayed in grid view.

**Comment by kasvith** [comment]
is this for dropbox ?

**Comment by kasvith** [comment]
the reason is the getSafeFilename does not work with spaces, originally they replace ' ' with '_'

**Comment by kasvith** [comment]
@laoneo @dneukirchen

**Comment by laoneo** [comment]
Marked it as bug.

**Comment by kasvith** [comment]
This is solved in #358
