### ISSUE TITLE
clean php-codesniffer warnings in administrator/com_media

### ISSUE THREAD

**Issue by marcodings** [joomla-projects/media-manager-improvement#35]
clean php-codesniffer warnings in administrator/com_media

in php-storm run "code|inspect code" on each file

**Comment by laoneo** [comment]
Closing this issue as part of a repository cleanup for milestone 1 https://github.com/joomla-projects/media-manager-improvement/wiki. If you still think this issue exists on milestone 1, don't hesitate to reopen it.
Thanks for understanding.
