### ISSUE TITLE
[Feature] Column changer for grid view

### ISSUE THREAD

**Issue by ciar4n** [joomla-projects/media-manager-improvement#353]
Add -/+ icons to tool bar to change the number of columns in grid view. 

Applied to width property of `.media-browser-item` through the following values...

- width: calc(12.5% - 20px);
- width: calc(14.28% - 20px);
- width: calc(16.66% - 20px);
- width: calc(20% - 20px);
- width: calc(25% - 20px);
- width: calc(33.33% - 20px);
- width: calc(50% - 20px);
- width: calc(100% - 20px);

**Comment by dneukirchen** [comment]
#362
