### ISSUE TITLE
State issue when opening nmm in subfolder

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#381]
### Steps to reproduce the issue

Open media managaer in subfolder

Click on "images" in tree menu

sampledata appears as a file, not a folder...

**Comment by kasvith** [comment]
I think we should not reproduce the tree

**Comment by dneukirchen** [comment]
@kasvith we need to reproduce it for ui reasons. 
at least in a minimal version on client side using the path.
