### ISSUE TITLE
Implement basic categories

### ISSUE THREAD

**Issue by marcodings** [joomla-projects/media-manager-improvement#39]
https://github.com/joomla-projects/media-manager-improvement/wiki#categories

Implement basic categories for media

Introduce the nessecary associated database fields for media
parent_id
category_id

**Comment by laoneo** [comment]
Closing this issue as part of a repository cleanup for milestone 1 https://github.com/joomla-projects/media-manager-improvement/wiki. If you still think this issue exists on milestone 1, don't hesitate to reopen it.
Thanks for understanding.
