### ISSUE TITLE
fix houndci-bot code style

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#399]
see https://github.com/joomla/joomla-cms/pull/18145

**Comment by ciar4n** [comment]
I'll fix this now.

If hound is going through these folders on the main repo maybe it should be added to this one to?

**Comment by dneukirchen** [comment]
Thx! 
Yes, lets add the houndci checks to this repo.

**Comment by dneukirchen** [comment]
thx @ciar4n
