### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/media-manager-improvement#404]
Using aria-hidden = true on the icons is not enough to satisfy accessibility.
For example with the current code what you are doing is completely removing all the meaning from the icons function

As an example none of the icons in the media-view-icons div have any text so with any assistive technology they are invisible

It doesnt need an a11y review to know that everytime you have an icon with aria-hidden=true you need to have some meaningful text for assistive technology.

It is all documented here http://fontawesome.io/accessibility/ so it is a waste of the a11y time to comment on this when it is easy to do and a known issue with a known fix.

Let the a11y team concentrate on reviewing the issues that we dont know about

**Comment by ciar4n** [comment]
Would simply adding an aria-label be sufficient?

**Comment by brianteeman** [comment]
As per the link to fontawesome`s great resource. That would be ok on INTERACTIVE elements only and it must be on the href

**Comment by ciar4n** [comment]
PR created to aria-label to toolbar and grid item icons... #420

**Comment by dneukirchen** [comment]
closing this one. thx @ciar4n & @brianteeman  
Lets create new issues for further a11y improvements in milestone https://github.com/joomla-projects/media-manager-improvement/milestone/5.
