### ISSUE TITLE
Only work with media files

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/media-manager-improvement#416]
**This is really bad.** It can open up the entire web site to anyone with media manager access. Remember that can include low level users. Presumably (although currently broken) the media manager will be used on the front end as well. Making this even more dangerous.

 As can be seen below I have opened up the site to allow anyone to delete or rename any file - including php - on the site

<img width="468" alt="screenshotr15-06-10" src="https://user-images.githubusercontent.com/1296369/30971998-500ae1f2-a461-11e7-81a8-6df801199271.png">
<img width="457" alt="screenshotr15-07-05" src="https://user-images.githubusercontent.com/1296369/30971997-5000555c-a461-11e7-90b3-824c3ae7fce6.png">
<img width="393" alt="screenshotr15-06-26" src="https://user-images.githubusercontent.com/1296369/30971996-4fe9d05c-a461-11e7-813f-f78721e29048.png">

**Comment by brianteeman** [comment]
@dneukirchen  this is a critical issue and it cannot be merged without this being fixed

**Comment by kasvith** [comment]
How anyone without admin rights can use media manager?

**Comment by dneukirchen** [comment]
Yes, thx @brianteeman 
We will resolve this asap. Should be an easy fix.

**Comment by brianteeman** [comment]
@kasvith at the front end when creating an article. Also a low level admin user with just access to create content in the admin

**Comment by kasvith** [comment]
We will add user level permissions to NMM later, for now we would just filter the *.php* files from the rest

**Comment by brianteeman** [comment]
NO! It is nothing to do with permissions. That is not the correct way. You should only be displaying defined media files. You should not be hardcoding anything to filter out files. Simply filtering out *.php is nowhere near enough. What about js etc. 

Please look at the current media manager. It only displays files that are set in the options for Legal Extensions (File Types). NMM is ignoring this setting and this is the correct way to do this - a user controlled WHITELIST of allowed files

**Comment by laoneo** [comment]
If you put a .php file into the images folder in the old media manager, then it does show this file. So we are not badder as the old one. But we want to move forward, #419 should only serve and work with files which are configured as allowed file types in the settings.

**Comment by brianteeman** [comment]
> If you put a .php file into the images folder in the old media manager, then it does show this file. So we are not badder as the old one

The problem was that the new local storage option exposed the entire folder tree and users are stupid.

Going to close this as #419 resolves this
