### ISSUE TITLE
front end broken

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/media-manager-improvement#417]
Testing on the front end and I always get

`Warning: require_once(C:\Apache24\htdocs\cms4\administrator/components/com_media/media.php): failed to open stream: No such file or directory in C:\Apache24\htdocs\cms4\components\com_media\media.php on line 18`

**Comment by laoneo** [comment]
Please test #429, it should fix the issue.

**Comment by brianteeman** [comment]
I would test it but the branch has a 500 error on the front end

500 Expression #1 of ORDER BY clause is not in SELECT list, references column 'nmmtest1.c.lft' which is not in SELECT list; this is incompatible with DISTINCT

**Comment by laoneo** [comment]
Did you do a fresh installation?

**Comment by brianteeman** [comment]
yes

**Comment by laoneo** [comment]
I didn't do a new installation, if there is such an issue, then we have it probably in 4.0-dev as well as we didn't change something on that part.

**Comment by brianteeman** [comment]
Sorry - yes you are correct - its broken upstream
