### ISSUE TITLE
Path to files/images

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/media-manager-improvement#418]
Now that we have the local file storage plugin is there any need for the options below. Do they even have any effect.

<img width="376" alt="screenshotr10-02-47" src="https://user-images.githubusercontent.com/1296369/31008835-5eee75ca-a4fd-11e7-8dca-0fcba83de79c.png">

**Comment by laoneo** [comment]
I guess we need to discus that in the main repo as it will be a rather hard BC break, if we remove the options. @kasvith opened an issue for it already https://github.com/joomla/joomla-cms/issues/18035.
