### ISSUE TITLE
J!4 - a recommendation for the removal of breadcrumbs on the Media Manager screen

### ISSUE THREAD

**Issue by rgmears** [joomla-projects/media-manager-improvement#424]
The current J!4 Media Manager screen looks like this:

![j4-media-manager-original-1](https://user-images.githubusercontent.com/4270063/31018587-4daa960a-a4f2-11e7-953f-4c5c88c23030.gif)

On this issue https://github.com/joomla-projects/media-manager-improvement/pull/394 I recommended a couple of changes which led to this screenshot where the breadcrumbs are gone and the images pane maximizes the height of the window (on wide screens).

![j4-media-manager-4](https://user-images.githubusercontent.com/4270063/31018742-bf549698-a4f2-11e7-8231-b11583ec9d1f.gif)

I understand the argument for using breadcrumbs, however, to me they are redundant in this the only backend page in Joomla which uses breadcrumbs.

**Comment by brianteeman** [comment]
As already explained to you. Breadcrumbs are essential for accessibility especially if you have a visual or cognitive impairment.

Joomla has an accessibility policy which you can read here https://www.joomla.org/accessibility-statement.html

It is not about **YOU** and if they are redundant to **YOU** - it is about **everyone** even if you don't believe that someone with a visual or cognitive impairment should be able to use Joomla it is not **YOUR** decision to make.

**Comment by dneukirchen** [comment]
I like the clean approach with more space in the main area, but as explained in PR 394 i also think that we should keep it. Imo the little more gain in space is not worth loosing orientation / accessibility and an additional navigation element.

**Comment by rgmears** [comment]
Not sure why you're so worked up about this @brianteeman. 
It's just a suggestion. It would be worth finding out whether people rely on the breadcrumbs or not. I don't, but I'm willing to allow that others might.

**Comment by rgmears** [comment]
I also don't know how many visually impaired people use Joomla!. But I do know that the 12 pixel text used throughout the backend must be a problem for them. No one has noticed that I made the toolbar buttons bigger and increased the size of the text

**Comment by brianteeman** [comment]
sorry - ignorance again - you can easily increase the font size in your browser. 

How many people is irrelevant. It would be the same if it was one or one million

I am worked up - as you say - because you are making ignorant and offensive comments that devalue the worth of people with disabilities and question if they have the right to use Joomla.

Not wasting any more time on this or you

**Comment by laoneo** [comment]
@brianteeman please calm down. I guess @rgmears didn't want to make any offensive comments against disabled people.
People are so much used to have a breadcrumb, not sure if we can remove it. But what can be done for sure is to have less margin on the top and bottom.

**Comment by rgmears** [comment]
Best not to jump to judgement Mr. Teeman. 
Here's the Media Manager page with the font size increased in the browser:
![j4-media-manager-large-text](https://user-images.githubusercontent.com/4270063/31021509-ac87ac36-a4fb-11e7-90b0-0db6e53f887d.gif)

**Comment by brianteeman** [comment]
statements such as this are ignorant at best and offensive at worst. it is a sad day when we make apologies for anyone making comments like this

<img width="620" alt="screenshotr14-05-13" src="https://user-images.githubusercontent.com/1296369/31021649-65e20956-a52e-11e7-8c29-36238ee99a37.png">

**Comment by mbabker** [comment]
Intended or otherwise some of the comments are coming across with a very strong bias toward "disabled users are not a priority".  And that is where the issue lies for at least two of us.

**Comment by rgmears** [comment]
I did not say or intend in the least that disabled users are of no consequence. Or that they do not use Joomla. As far as it goes here, I have to increase the font size on a lot of websites I visit in order to read them. You won't know this Michael but I actually contacted Brian some time ago about the faulty way in which his own website scales font sizes and he brushed me off. So while he is pouncing on me his own website is unreadable by anyone who is visually impaired.

**Comment by brianteeman** [comment]
it is perfectly readable you just dont like the styling - and that is completely irrelevant

**Comment by brianteeman** [comment]
Media Manager with zoomed in the browser works perfectly for me - this is at 200%

<img width="1017" alt="screenshotr16-15-18" src="https://user-images.githubusercontent.com/1296369/31022672-72efcac2-a531-11e7-94d0-210e69fbd240.png">

**Comment by rgmears** [comment]
When we corresponded Brian I said nothing about the styling. I only observed that one block of text was distorted/cut off. I'm not sure which browser you use but in Firefox both the Joomla backend and your website do NOT scale up appropriately.

**Comment by dgrammatiko** [comment]
Just to mention that goals for front end and back end templates are:
- fully accessible with keyboard
- comply to WCAG 2 level AA

Whatever suggestion violates these two (there are quite a few more requirements) should be closed. There’s no reason for all of us to waste time on something that doesn’t fit the prerequisites

**Comment by rgmears** [comment]
@brianteeman, seems we're both right, or wrong, as the case may be. 
If you zoom in with "Zoom Text Only" selected you get what I showed in the screenshot.  
If "Zoom Text Only" is NOT selected you get what your screenshot shows.
I guess I'm cognitively challenged. 

@dgt41, I don't see what the WCAG 2 level AA recommendations have to do with breadcrumbs.

**Comment by brianteeman** [comment]
it has already been explained

**Comment by rgmears** [comment]
No @brianteeman,  I've been told. 
WCAG 2 level AA recommendations are rather vague. And, it seems to me that having breadcrumbs on the Media Manager page will only confuse people. However, I, too, have nothing more to say on this matter.
