### ISSUE TITLE
J!4 - Admin pages do not zoom in properly with "Zoom Text Only"

### ISSUE THREAD

**Issue by rgmears** [joomla-projects/media-manager-improvement#425]
### Steps to reproduce the issue
Go to any page in the Admin section. Select "Zoom Text Only" under View in the browser menu. 
Either CTRL/scroll in or go to View > Zoom > Zoom In

### Expected result
![j4-media-manager-zoom-in](https://user-images.githubusercontent.com/4270063/31045144-8b1b3c50-a5a2-11e7-9790-88dbccf45f00.gif)

### Actual result
![j4-media-manager-zoom-in-text](https://user-images.githubusercontent.com/4270063/31045148-9df32568-a5a2-11e7-8b0b-fbf48267d2be.gif)

### System information (as much as possible)
Joomla! 4 Administration

### Additional comments
I do not know how to fix this. Am simply bringing it to people's attention.

**Comment by dneukirchen** [comment]
Does this affect every admin page or just the media manager?

**Comment by rgmears** [comment]
All pages.

**Comment by dneukirchen** [comment]
Then this is an issue of the new Admin Template not of the Media Manager. Would be nice if you open this issue in the main repository. Thank you!

**Comment by rgmears** [comment]
How do I get to the main repository?

**Comment by dneukirchen** [comment]
https://github.com/joomla/joomla-cms

**Comment by rgmears** [comment]
[Done](https://github.com/joomla/joomla-cms/issues/18181)
