### ISSUE TITLE
Copy public file url to clipboard

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/media-manager-improvement#430]
A feedback on Jday Germany was to copy the public file url of a media file to clipboard.

**Comment by kasvith** [comment]
we need a toolbar button for that

**Comment by dneukirchen** [comment]
add an icon-button next to the path in the media infobar.

**Comment by kasvith** [comment]
This should be work only on files IMO

**Comment by kasvith** [comment]
@dneukirchen i dont agree adding a button next to the path, since this should be explicitly work on files rather than folders, so my suggestion is to popup an icon on files or when a file is selected show a tool bar icon to copy url

**Comment by kasvith** [comment]
another suggestion is to add a button before delete icon

**Comment by laoneo** [comment]
I would also add it to the action buttons here
![image](https://user-images.githubusercontent.com/251072/34664874-4941a520-f45e-11e7-8ffc-2dccf76dd570.png)

**Comment by kasvith** [comment]
yeah agreed, rather than creating a toolbar button this is better

**Comment by dneukirchen** [comment]
i do not agree here. We should not put so many actions in the quick button menu. At least in its current form it is meant to hold only the most important actions.

**Comment by ciar4n** [comment]
I with David on this, already feels like one to many actions.  I'm not against placing the action here, just think we need to reconsider how they are displayed.

**Comment by kasvith** [comment]
hmm, then we have to enable this button on toolbar when user clicks only a single file. 
Let me know when you guys finalized this. Putting icon on file makes it simple, but as mentioned it overwhelm the file icon too.
 
let me know @dneukirchen @laoneo @ciar4n

**Comment by ciar4n** [comment]
For the time been I'd say add it here...

![image](https://user-images.githubusercontent.com/2803503/34719227-d860a12e-f531-11e7-9619-4d1828033562.png)

I think we just need to reconsider how these icons are displayed which can be done after.

**Comment by laoneo** [comment]
I would also not start spreading the actions all over the UI which are related to an item. Perhaps we need to reconsider the action drop down, but actions which do belong to an item (file, image, video, etc.) should appear close to it. At the moment it is the drop down.

**Comment by dneukirchen** [comment]
I do not fully agree, but im ok with it. 

imo copy path to clipboard is different than the primary actions like rename, remove, delete, move... its a more like a convenience helper. Imo Inline menus should be 100% intuitive and users should not have to search for the action they want to use... We should also keep in mind that we need the inline menu in the table view as well.

**Comment by laoneo** [comment]
Perhaps you can post a screenshot where you want to add the icons to copy it? Perhaps I did get your idea wrong.

**Comment by ch2856** [comment]
Since the system now remember the last path in media manager, I don't see a reason to add this.

**Comment by laoneo** [comment]
It's about copying the public oath which you can use then as link in an image tag or send by mail.

**Comment by kasvith** [comment]
PR - #531

**Comment by kasvith** [comment]
Done in #531 and closing issue
