### ISSUE TITLE
Fix breadcrumbs

### ISSUE THREAD

**Issue by dgrammatiko** [joomla-projects/media-manager-improvement#438]
### Steps to reproduce the issue
Create some nested folders (a few of them), observe the breadcrumbs 

<img width="1089" alt="screen shot 2017-10-06 at 15 14 37" src="https://user-images.githubusercontent.com/3889375/31279411-49cac7dc-aaa9-11e7-8623-1cf59fd36ede.png">

### Expected result

Not broken

### Actual result

Broken

### Additional comments

Possible solutions:
- make them horizontally scrollable
- use js and a similar approach as pagination (1 2 ... 18)

**Comment by kasvith** [comment]
i think we need to hide some intermediate steps, like windows does

**Comment by dneukirchen** [comment]
something like https://bootsnipp.com/snippets/featured/responsive-breadcrumbs ?

**Comment by ciar4n** [comment]
Hiding the top level items seems like a logical solution

**Comment by brianteeman** [comment]
You would need to check with a11y team but i "think" that if you are hiding the top level items (which seems a good idea to me) then you might need to do it so that they are only hidden visually

**Comment by kasvith** [comment]
like this, A > B > C > D > E > F is transformed into A > B > ... > E > F, once you go to E if there is enough space it will show full path

**Comment by brianteeman** [comment]
... >C > D > E > F

**Comment by kasvith** [comment]
nope i dont like that, check Windows Explorar, it does it neatly

**Comment by dgrammatiko** [comment]
@kasvith don't ever quote windows, they're always doing it wrong 😂

**Comment by brianteeman** [comment]
Windows 10 does it exactly how i said. See these two screenshots
<img width="399" alt="screenshotr10-48-35" src="https://user-images.githubusercontent.com/1296369/31315740-5aaca0fc-ac16-11e7-9d02-e07782fcb4d9.png">
<img width="782" alt="screenshotr10-48-44" src="https://user-images.githubusercontent.com/1296369/31315741-5aadc7ac-ac16-11e7-937d-e5f13da9d7c9.png">

**Comment by kasvith** [comment]
ok my bad, no windows for months lol
