### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by dgrammatiko** [joomla-projects/media-manager-improvement#439]
### Steps to reproduce the issue

Alerts are hard to customise, esp the buttons.
Proposal: 
- Keep the custom element
- Extend the custom element and introduce a new function eg `createButton`
- Then a single line should be enough for run time additional buttons with custom functionality: 
```js
element.createButton(
{
     'classes': 'btn btn-success',
     'dismiss': true,
     'text': 'Click me',
     'callback': someFunction
});
```

If this is ok we need to redesign the alerts a bit so we always get buttons and not the bootstrap X thing.

@laoneo @dneukirchen @ciar4n thoughts?

**Comment by kasvith** [comment]
this seems nice thumbs up

**Comment by laoneo** [comment]
Would that code then be in the MM app? The classes attribute looks for me wrong as I have to provide bootstrap specific classes to the custom element.

**Comment by dneukirchen** [comment]
like the idea. 👍
