### ISSUE TITLE
Implement A11Y proposals

### ISSUE THREAD

**Issue by dgrammatiko** [joomla-projects/media-manager-improvement#443]
Once we get the feedback from the accessibility team (https://github.com/joomla/accessibility/issues/32) the proposals needs to be coded.

(In combination with the input from UX/Design teams)

**Comment by brianteeman** [comment]
is this in process?

**Comment by dgrammatiko** [comment]
Yeah, we are in the process to setup a dummy server for them

**Comment by armenos** [comment]
How to get involved? 
I'll ask JAT Test&Auditing to join.

**Comment by dgrammatiko** [comment]
Since the auditing has already started, this issue is obsolete
