### ISSUE TITLE
Add a task bar for batch processing (move, etc)

### ISSUE THREAD

**Issue by marcodings** [joomla-projects/media-manager-improvement#45]
Add a task bar for batch processing (move, etc)

https://github.com/joomla-projects/media-manager-improvement/wiki#categories

**Comment by laoneo** [comment]
Closing this issue as part of a repository cleanup for milestone 1 https://github.com/joomla-projects/media-manager-improvement/wiki. If you still think this issue exists on milestone 1, don't hesitate to reopen it.
Thanks for understanding.
