### ISSUE TITLE
Close preview

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/media-manager-improvement#450]
The close icon on the image preview is so far from the image preview itself (if its a relatively small image) that it is almost impossible to find

see screenshot
<img width="1278" alt="screenshotr18-03-18" src="https://user-images.githubusercontent.com/1296369/32066624-4d796468-ba78-11e7-9ae4-7e11ed9717a9.png">

**Comment by ciar4n** [comment]
I think it should be pretty acceptable to have the close in the top right corner. The is inline with Twitter, Facebook, Dribbble, Pinterest and Google+ (top left). I'm sure the list goes on as these are the first 5 I've checked.

**Comment by ciar4n** [comment]
Maybe the backdrop could be darken'd which would make the close stand out a bit more.

**Comment by brianteeman** [comment]
Yes it definitely needs darkening - similar to twitter

However this use case is not identical to twitter. Twitter is typically offering you this when it has a large image to display and so it fills more of the screen. Hopefully web site owners are not using such large images so the disconnect is more extreme. 

Also the image name is directly above the preview so you dont look in the top right. if the image name was at the top of the screen then maybe you would see the X more easily

<img width="1280" alt="screenshotr20-59-22" src="https://user-images.githubusercontent.com/1296369/32074251-b7bd854e-ba90-11e7-8002-e76d6a028ad6.png">

**Comment by ciar4n** [comment]
Personally I have just gotten use to expecting close options in the top right corner. I'm easy either ways so not against changing it. An issue with putting it inline with the current image title is the possibility of them overlapping (consider #449). Maybe placing both title and the close in a bar across the top as you suggest might be the best option. 

Dropbox been one example...

![image](https://user-images.githubusercontent.com/2803503/32075709-807ebbd4-ba95-11e7-84f3-34a365a47a89.png)

**Comment by brianteeman** [comment]
Notice how dropbox has a similar design pattern to twitter. The filename is at the top of the screen so you are already drawn to the top of the screen. nmm has the filename directly above the image so you dont look at the top. move the filename to the top of the screen and problem solved (and increase the backdop darkness)

**Comment by ciar4n** [comment]
Pr created.. #461
