### ISSUE TITLE
Select all

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/media-manager-improvement#452]
I am assuming that the checkbox before the breadcrumbs is a select all.

I would expect it to be checked ONLY when everything is selected and not checked only when nothing is selected.

The current behaviour is the opposite
<img width="778" alt="screenshotr20-25-25" src="https://user-images.githubusercontent.com/1296369/32072834-f97cf0fa-ba8b-11e7-96b4-59c4fafba6b6.png">

**Comment by ciar4n** [comment]
I'd agree with you on this. Considering this is a toggle is makes sense that the icon represents the current state.

**Comment by brianteeman** [comment]
especially as that is the behaviour throughout the rest of the joomla ui

**Comment by laoneo** [comment]
The first implementation was like that in #363. But after playing with it, we agreed to change it to the opposite in #373.

**Comment by brianteeman** [comment]
Then you changed it wrongly. If you look at every other "select all" checkbox in the joomla ui the unselected state is an unchecked box. Also from an a11y perspective it must be unchecked for unselected otherwise you run into all sorts of issues trying to override the default behaviour of assistive technology

**Comment by dneukirchen** [comment]
thx.
