### ISSUE TITLE
Zoom icons

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/media-manager-improvement#454]
<img width="253" alt="screenshotr20-28-29" src="https://user-images.githubusercontent.com/1296369/32072921-455cdf80-ba8c-11e7-9e3b-ca76a42df29b.png">

I didnt realise these were zoom icons. I assumed they were add/delete icons. I would normally expect to see the fa icons search-plus/minus icon or something like that

**Comment by ciar4n** [comment]
So... 

![image](https://user-images.githubusercontent.com/2803503/32075987-5bf6add4-ba96-11e7-9015-ea8a95bf5ce8.png)

Makes sense.

**Comment by brianteeman** [comment]
Yes it does

**Comment by ciar4n** [comment]
PR created #460
