### ISSUE TITLE
hardcoded string

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/media-manager-improvement#458]
https://github.com/joomla-projects/media-manager-improvement/blob/f4a7e4c655da6693e0b6d485787698ec99fd8ee6/administrator/components/com_media/resources/scripts/store/actions.js#L120

This needs to be a translatable string. In addition it should say in en-GB
**already exists. Do you want to overwrite it?**

Note a grep shows me this string in several places but as i dont know vue (yet) i dont know if this is the only place it needs to be fixed

<img width="410" alt="screenshotr20-48-00" src="https://user-images.githubusercontent.com/1296369/32073942-b95c50c0-ba8f-11e7-82e8-b02fe5828e9e.png">

**Comment by dneukirchen** [comment]
thx
