### ISSUE TITLE
Security Issue in [4.0Alpha] 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-projects/media-manager-improvement#466]
want me to post it here, or want me not to post it here?

**Comment by laoneo** [comment]
Got the info from George. Will have a look. Thanks for testing.

**Comment by laoneo** [comment]
I made some changes and forwarded it to the JSST team.

**Comment by laoneo** [comment]
Fix got merged already into upstream with confirmation of the JSST team at JWC. Thanks for reporting.
