### ISSUE TITLE
[4.0Alpha] Its TOO easy to delete whole folders

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-projects/media-manager-improvement#469]
When I clicked a folder, and then clicked delete, it deleted the whole folder, and all images, with no confirmation, and no warning.... gone... all my images.... (ok so this was a test only, but idiots will delete everything and blame Joomla, so this has to be made more difficult for a user to destroy their site, at least warn them if deleting a folder recursively !!!)

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/20367

**Comment by laoneo** [comment]
This is a duplicate of #437.
