### ISSUE TITLE
Update JMM fork met upstream van joomla/joomla-cms

### ISSUE THREAD

**Issue by jissereitsma** [joomla-projects/media-manager-improvement#47]
The current source of this project runs being the `joola/joomla-cms` project. Upstream needs to be added (`git remote add upstream git@github.com:joomla/joomla-cms.git`) and merged - this leads to various PHP Fatal Errors that need to be resolved.

**Comment by brianteeman** [comment]
even without merging upstream there are fatal errors

**Comment by laoneo** [comment]
Closing this one as we start from scratch and staging is now up to date again with upstream.
