### ISSUE TITLE
[4.0Alpha] faked url has undefined offset

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-projects/media-manager-improvement#470]
### Steps to reproduce the issue

fake a call to http://0.0.0.0:8010/administrator/index.php?option=com_media&format=json&task=api.files&url=true

### Expected result

No path disclosure

### Actual result

```
Notice: Undefined offset: 1 in /Users/phil/Downloads/joomla-cms-4.0.0-alpha1/administrator/components/com_media/Controller/ApiController.php on line 444
{"success":false,"message":"Account was not set","messages":null,"data":null}
```

**Comment by laoneo** [comment]
Can you please check if #472 fixes the issue?

**Comment by laoneo** [comment]
Issue can be closed as the pr got merged. Thanks for reporting.
