### ISSUE TITLE
select all/deselect all is opposite to expected behaviour

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-projects/media-manager-improvement#473]
### Steps to reproduce the issue

![screen recording 2017-11-19 at 07 25 pm](https://user-images.githubusercontent.com/400092/32994451-7a848a10-cd5f-11e7-8949-67ce2e92dae6.gif)

### Expected result

The accepted behaviour for a select all checkbox is normally

 - if you see it is empty and you click it, it becomes checked, and all items are checked
 - if you see it checked and you click it, it becomes unchecked, and all items are unchecked 

Expected result = behaviour consistent with other checkbox select alls, conforming to the norm...

### Actual result

The total opposite to accepted norms. 

### System information (as much as possible)

Joomla 4 Alpha 1/2

**Comment by brianteeman** [comment]
duplicate of #459

**Comment by PhilETaylor** [comment]
I disagree - this is not a duplicate, this one is more about the select all/deselect all icon presented in the interface, not like #459 which is about selecting individual or groups of items a different way.

**Comment by brianteeman** [comment]
sorry i meant #452

**Comment by PhilETaylor** [comment]
yup - thats more like a duplicate :) :)
