### ISSUE TITLE
Accepted norm for + and - is not to zoom in

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-projects/media-manager-improvement#474]
### Steps to reproduce the issue

Click on these
![screen shot 2017-11-19 at 19 26 23](https://user-images.githubusercontent.com/400092/32994460-92658f12-cd5f-11e7-87d8-7bc9d35ee402.png)

### Expected result

Expect + to be "Add a file or folder"
Expect - to, well dunno...
I DONT expect them to be the icons for zoom in and zoom out, 

### Actual result

Zoom in and out

**Comment by brianteeman** [comment]
this was solved with #460 i "guess" that the updates havent been pushed to the joomla-cms repo

**Comment by PhilETaylor** [comment]
Wonderful...
