### ISSUE TITLE
"save as copy" button

### ISSUE THREAD

**Issue by micker** [joomla-projects/media-manager-improvement#476]
i think we need a
"save as copy" button : when we rezize image we need to keep original image ... a simple save as copy can be good
maybe it will be a default button for all modifications

**Comment by laoneo** [comment]
Sounds like a nice idea, somebody else was requesting that on twitter as well https://twitter.com/tbachner/status/939063238192435200

**Comment by laoneo** [comment]
Closing this as duplicate of #385.
