### ISSUE TITLE
Recompile SCSS

### ISSUE THREAD

**Issue by C-Lodder** [joomla-projects/media-manager-improvement#477]
I've made a couple of direct commits to remove some inline CSS and fix the stacking issue for one of the close buttons.

Not sure how you're compiling SCSS on here so leaving this issue open as a reminder

Ping @ciar4n

**Comment by laoneo** [comment]
Thanks. npm run build in the com_media folder of you want to do it.

**Comment by C-Lodder** [comment]
ah fair enough. I'll do that later on tonight

**Comment by ciar4n** [comment]
You will find all the commands here.. #346 

PR created recompiling.. #478

**Comment by C-Lodder** [comment]
Thanks Ciaran
