### ISSUE TITLE
[4.0] Unexpected error on  rename of file or folder.

### ISSUE THREAD

**Issue by anuragteapot** [joomla-projects/media-manager-improvement#487]
### Steps to reproduce the issue
Try to change folder or file name.

### Expected result
No error comes.

### Actual result
An error comes out.
![screenshot from 2018-01-10 23-18-42](https://user-images.githubusercontent.com/30978328/34788773-9d28fbc0-f661-11e7-87dd-d5974c8dd51d.png)

### System information (as much as possible)
Joomla 4.0-dev
OS Linux
PHP 7.1.11 

### Additional comments
File or folder renamed without any issue

**Comment by kasvith** [comment]
After taking this action, if we refreshed the page, the renamed item is visible as usual.
So this is a problem in the Client, not the Server(tested on Windows 10)

Items are renamed, but client shows an error

**Comment by anuragteapot** [comment]
yes, Items are renamed without any issue but client shows an error

**Comment by kasvith** [comment]
Can you try to fix that :)

**Comment by anuragteapot** [comment]
@kasvith Ok, let me try :)
