### ISSUE TITLE
Create Joomla\MediaManager 

### ISSUE THREAD

**Issue by jissereitsma** [joomla-projects/media-manager-improvement#49]
Create a new library under `libraries/vendor/joomla-projects` and have it include a `Joomla\MediaManager\Image\ActionInterface` interface.

**Comment by laoneo** [comment]
Closing this issue as part of a repository cleanup for milestone 1 https://github.com/joomla-projects/media-manager-improvement/wiki. If you still think this issue exists on milestone 1, don't hesitate to reopen it.
Thanks for understanding.
