### ISSUE TITLE
Bug: Width-height ratio on cropping

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/media-manager-improvement#490]
### Steps to reproduce the issue
1. Click on one of the radio buttons. The radio button do not get checked.
2. More important - If you once click on one of the radio buttons you are trapped. You can choose another ratio but not reset to "free" width/height. Another radio button or a reset button is needed. I think I would prefer a reset to original start values (images width and height).

**Comment by laoneo** [comment]
True.

Please open for every problem one issue, it helps keeping the focus.

**Comment by schnuti** [comment]
I think the two issues are that close related that they should stay together.

**Comment by laoneo** [comment]
Can you please test #492 which should fix point 2.

@dgt41, @C-Lodder or @ciar4n any clue why the radio buttons do not work propperly? Something broken in core?

**Comment by schnuti** [comment]
Part 2 has a PR 492 and an issue for part 1 has bin added.
