### ISSUE TITLE
Ratio radio buttons do not get checked in Crop view.

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/media-manager-improvement#494]
### Steps to reproduce the issue
Click on one of the ratio radio buttons in the image crop view. The radio button do not get checked. 

### Expected result
That the radio button get checked.

### Additional comments
Issue #490 splitted up in two as part 2 has a PR.

**Comment by laoneo** [comment]
@dgt41, @C-Lodder, @ciar4n is this a bug in core?

**Comment by C-Lodder** [comment]
@laoneo I don't believe so. Last time I tested the radio buttons in core, they worked as expected.

**Comment by laoneo** [comment]
As far as I could debug it, the MM does not interfere with the checkboxes. Honestly I have no clue what is going on here. There is no reason for the current behavior.

**Comment by schnuti** [comment]
@laoneo 
I think I found the problem. Until there is a solution to replace the radio buttons with pseudo buttons use standard. i.e. **remove the classes** from the radio fields in the form.
class="btn-group btn-group-ratio" and do not add any class to the options.

**Comment by laoneo** [comment]
Thanks, pr got merged.
