### ISSUE TITLE
Distinct values for image rotate

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/media-manager-improvement#495]
### Steps to reproduce the issue
If you rotate an image to other values than 90, 180, 270 degrees the image gets cut off. 

### Proposal
A canvas resize to fit the whole image. I know it's harder to achive but you could then make some minor rotation without cutting off the image.
Alternative: Use radio buttons for the distinct values 90, 180, 270, (360) degrees. I see that 90 and 270 degrees are handled correct.
Alternative 2: Keep the free rotation AND add distinct values with radio buttons.

**Comment by ciar4n** [comment]
For me it would make sense to have the resize and rotate on the same panel as you would rarely do one without the other. Slightly off topic and probably not possible.

Example... most likely a user would zoom this image to remove the black corners. 

![image](https://user-images.githubusercontent.com/2803503/35038514-f10254ce-fb72-11e7-8c75-43795c41e7a7.png)

**Comment by ciar4n** [comment]
@schnuti I think what you suggest is a good idea. My preference would be keep the free rotation AND add distinct values with radio buttons.

**Comment by schnuti** [comment]
@ciar4n Please have a look at PR #496 for testing this. I kept free rotation but with a number field type where you can type in the degrees **OR** use the steps. I skipped the slider.

I do not think you can fix the black corners by zooming the image as the zoom is done including the black corners (the canvas). You could crop the image to get rid of the black corners if you didn't rotate to much. That's why I say that it should be possible to enlarge the image when resizing.  Rotate - crop to remove black corners - enlarge to original or wanted size. Am I right? I only believe so, not quite sure. 

When merging my patches on GitHub my change of the image quality fields to number field types got included (not planed)
You normally know what you want to use, the default 80 or 90, 75, 70 or whatever and you enter it directly. You do not want to open a long list with numbers from 1 to 100 (integer field type)

**Comment by ciar4n** [comment]
Sorry you are right.. I meant to say crop not resize.

**Comment by schnuti** [comment]
I found that the workflow I described works as is.
You are able to enlarge the image. Enter the width or height in the field. DO NOT touch the sliders! There is no check on max width / height for the input fields.
I think though that separate width and height input must be possible i.e. to turn off the aspect ratio restriction. I know - not the best for quality images but you may need images with the same size.
There is an issue for that. #483

**Comment by schnuti** [comment]
And a last comment having nothing to do with this issue.
You can get the original size back after rotating using an additional step.
The resizing must get you an exact width or height and the other dimension larger.
As last step you now crop a second time to the exact original size.

**Comment by laoneo** [comment]
I would leave the slider, you can work faster when you can slide, when you don't know the angle. Always changing the number is way slower.
But I like the angle presets.

**Comment by schnuti** [comment]
@laoneo Did you test my PR? The number field type is more exact and as fast as the slider. Click and hold on the up and down arrows and it's really fast. e.g. click on fixed 90 degrees  - then the down button to step down to 45 degrees is a nice test. 
If possible I would enlarge those arrows. Not that easy as it's W3C standard and styled by the browser.
I find it gets cluttered with 3 different angle inputs.

**Comment by schnuti** [comment]
I found another way to rotate fast.
Click in the number field type and and use the mouse wheel to increase/decrease the value.

I really like this field type since the first time I used it.

**Comment by schnuti** [comment]
I have to change my mind. MS-Edge have minimal support for the number field type. So for this reason a slider is still needed. As a surprise, that is supported.
