### ISSUE TITLE
Replace radio buttons with pseudo buttons

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/media-manager-improvement#499]
To keep the radio buttons on a to-do list after #494 and PR #498 I added this issue.

### Expected result
Radio buttons with the look of normal buttons.

**Comment by laoneo** [comment]
I don't understand what exactly you want to change. Can you elaborate a bit more, perhaps with a screenshot?

**Comment by schnuti** [comment]
We have to wait until core has merged a couple of pending PR's for radio buttons but then buttons can replace the radio buttons. I think the new MM had it in the early days.
I think there's a need for some special styling as I see problems with the width of the grouped buttons. They are not responsive.
Image shows an example from a frontend view I use in J3 showing 4 radio buttons as buttons.
 
![radio-as-button](https://user-images.githubusercontent.com/956537/35083570-1b5f882e-fc20-11e7-97f2-09192f476fe3.jpg)

**Comment by laoneo** [comment]
Would be nice if you can link the related pr's here.

**Comment by schnuti** [comment]
PRs and issues of interest in core (maybe more) 
joomla/joomla-cms#19326 - PR Fix radio btn group
joomla/joomla-cms#19322 - Rewrite markup radio form field
joomla/joomla-cms#19296 - PR Split the radio Field to 2 layouts

**Comment by laoneo** [comment]
Thanks, so we wait?

**Comment by schnuti** [comment]
Better do nothing regarding radio buttons until core has a basic solution or everything may have to be reverted/redone.

**Comment by schnuti** [comment]
See PR 503

**Comment by schnuti** [comment]
Let's keep this as a todo - reminder for the radio buttons on the rotate view.

**Comment by schnuti** [comment]
Existing radio buttons resolved with #508
