### ISSUE TITLE
Create some sample action classes

### ISSUE THREAD

**Issue by jissereitsma** [joomla-projects/media-manager-improvement#50]
For samples see https://github.com/joomla-projects/media-manager-improvement/wiki/Image_Transformations

**Comment by yvesh** [comment]
We changed the functionality slightly there. Actions are now all plugin based (Extending MediaActionInterface), so it can be easily extended.

**Comment by laoneo** [comment]
Closing this issue as part of a repository cleanup for milestone 1 https://github.com/joomla-projects/media-manager-improvement/wiki. If you still think this issue exists on milestone 1, don't hesitate to reopen it.
Thanks for understanding.
