### ISSUE TITLE
Landscape and portrait aspect ratios

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/media-manager-improvement#502]
Isn't a choice between landscape and portrait aspect ratios needed for cropping?

Let's say you have a 16:9 image with a person in the middle. You may want to cut out an image 3:4 of this person. i.e. the aspect ratio is in "portrait" format.

As is, you have to do this "per hand" as 4:3 gives you a landscape format.

I've used "Base on width or height" as choice for my own cropping method but Landscape/Portrait are probably better understood.

(The aspect ratio 1:1 is missing. Often used for avatars, icons and more. I'll add it to another issue. )

**Comment by laoneo** [comment]
I would leave them, perhaps we should switch to a drop down as mentioned here #501 where we can add a text.

**Comment by schnuti** [comment]
What would you leave? What I try to say is, that you need double values for the aspect ratios. Yes, a drop down could replace the radio buttons.

Original aspect ratio (default as suggested by someone in another issue)
1:1
Landscape
5:4
4:3
3:2
16:9
Portrait
4:5
3:4
2:3
9:16
Free aspect ratio - no restrictions

This would be my complete list with the most common aspect ratios for images.

**Comment by schnuti** [comment]
I've rebuilt the aspect ratios to a list field. I believe this is a better way to present the aspect ratios. I'll have a look if I'm able to modify the JavaScript as well. Or what do you think?
Image 1: The list field (width?), Image 2: The list, Landscape and Portrait are headers (disabled options)

![aspect-ratio_1](https://user-images.githubusercontent.com/956537/35166415-22fa0b08-fd52-11e7-8af4-aa70e1afa640.jpg)

![aspect-ratio_2](https://user-images.githubusercontent.com/956537/35166432-30f1d768-fd52-11e7-8cdb-5faf05ea4b4b.jpg)

**Comment by schnuti** [comment]
See PR 503
