### ISSUE TITLE
Background problem: longer file names and image preview

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/media-manager-improvement#506]
The white image background in image preview is confusing if the width of the file name exceeds the width of the image. Example: a cropped "powered_by - Copy.png" The image is cropped after the a in Joomla.

![modal-view1](https://user-images.githubusercontent.com/956537/35971459-4d97bdac-0cce-11e8-957b-a9c9c3ccd73a.jpg)

With the browsers dev tools I added a class to use the existing image background class. (Is image-brackground a typo?) -  (Can't propose a fix as vue is involved).

```
<div class="media-modal-backdrop media-preview-modal">
...
   <div class="modal-content">
      <div class="modal-header">
         <h3 class="modal-title">shop-ad - Copyxxxxxxxxxxxxxxx.png</h3> 
...
      <div class="modal-body">
===>      <div class="image-brackground">  <===
            <img src="https://localhost/patch2/images/shop-ad%20-%20Copyxxxxxxxxxxxxxxx.png" 
....
...

Result:

![modal-view2](https://user-images.githubusercontent.com/956537/35972117-d3bb0bf8-0cd0-11e8-829d-c288f61355d7.jpg)

-- Image is not loading for some reason. ?

**Comment by laoneo** [comment]
I guess @ciar4n this one is for you.

**Comment by ciar4n** [comment]
Thank you @schnuti 

PR created..  #509
