### ISSUE TITLE
Initial draft of Image class

### ISSUE THREAD

**Issue by jissereitsma** [joomla-projects/media-manager-improvement#51]
Copy sample from wiki (https://github.com/joomla-projects/media-manager-improvement/wiki/Image_Transformations) to `libraries/`

**Comment by laoneo** [comment]
Closing this issue as part of a repository cleanup for milestone 1 https://github.com/joomla-projects/media-manager-improvement/wiki. If you still think this issue exists on milestone 1, don't hesitate to reopen it.
Thanks for understanding.
