### ISSUE TITLE
Edit image Rotate: Active quick button

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/media-manager-improvement#513]
No correlation between entered angle and the "quick" buttons. As i understand, it's a bit tricky to solve with Javascript and the code would run for each and every click on the arrows in the number field. A "softer" way is to use the same styling css for active and not active buttons. The active state is only used when you click on a button anyway. The valid angel comes from the number field.

Added CSS

````
.btn-group-rotate .btn-outline-secondary:not(:disabled):not(.disabled).active{
 color: #868e96;
background-color: #fff;
 border-color: #868e96;
}
.btn-group-rotate .btn-outline-secondary {
 color: #868e96;
 background-color: #fff;
 background-image: none;
 border-color: #868e96;
}
```

Result: 
The border comes from focus after clicking and disappear with the next click.
I added the second rule as this could be changed in the bootstrap.css/template.css
If the image doesn't appear, please copy the address and open it in the browser directly.

![quick-buttons](https://user-images.githubusercontent.com/956537/36061246-2b9e61e8-0e58-11e8-9407-6509da12b480.jpg)

I do not know how to add this css  via a PR.

**Comment by laoneo** [comment]
@ciar4n I guess this is your area. What do you think?

**Comment by ciar4n** [comment]
Presuming I understand you correctly, classes exist for the styling of each state. So to apply the `:focus` styling you can use the `.focus` class. The question is is it possible to apply them classes to the buttons in the btn-group when the input values corresponds with them buttons (eg. 90, 180 etc)?

Correct me if I have picked you up wrong here! 😄

**Comment by schnuti** [comment]
@ciar4n You missunderstood. I find the focus state CSS OK. But not the "active state"

Example in  image, I clicked on button 90 degrees, then changed the value field to 0. The image is not longer rotated but the 90 degrees button is still "active". We don't need this "active" state at all.

![90degrees](https://user-images.githubusercontent.com/956537/37571973-7d6b8f96-2b04-11e8-89fb-43a86b05e835.jpg)

**Comment by schnuti** [comment]
@ciar4n @laoneo 
After a second thought. Maybe those buttons should be created using normal HTML action buttons. They do not really belong to the form as radio buttons.
What do you think?

**Comment by laoneo** [comment]
I would leave them for now. Like that it can be declared in the form.xml. If we switch to regular buttons we need to do some workarounds.

**Comment by schnuti** [comment]
Yes, it's less workaround to only add some CSS rules to fix this issue, my two above or similar.

**Comment by laoneo** [comment]
Pr got merged.
