### ISSUE TITLE
Clicking Info Bar deselcting the selected file in browser

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#515]
### Steps to reproduce the issue

1. Open NMM
2. Open Info Bar
3. Click a file
4. Now you will see the info about file
5. Click anywhere in the info bar
6. File get deselected

### Expected result
File should be still selected as

### Actual result
It looses the focus

### System information (as much as possible)
Windows 10, XAMMP PHP7.0, Latest Chrome

### Additional comments
We want it not be deselected as some user may wanna copy details from the infobar

**Comment by kasvith** [comment]
issue fixed in PR #516

**Comment by kasvith** [comment]
Issue seems solved somehow. but i will keep the issue until further confirmation

**Comment by dneukirchen** [comment]
thx @kasvith
