### ISSUE TITLE
Close button is messed up

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#518]
### Steps to reproduce the issue
Open Media Infobar for a file which has a longer name
![image](https://user-images.githubusercontent.com/13379595/37292219-7973dbfa-2636-11e8-9a9c-a3494bc77b92.png)

### Expected result
Close icon to be fixed

### Actual result
Icon is messed up

### System information (as much as possible)
Windows 10 PHP7, Chrome

**Comment by kasvith** [comment]
@ciar4n any SASS magic :)

**Comment by geetanshu-m** [comment]
@kasvith this issue needs to be closed. PR: #519  Solves this issue.

**Comment by dneukirchen** [comment]
thx @proman24

**Comment by kasvith** [comment]
thanks @proman24
