### ISSUE TITLE
Problem while uploading an file.

### ISSUE THREAD

**Issue by geetanshu-m** [joomla-projects/media-manager-improvement#521]
### Steps to reproduce the issue

Upload a file to the media manager. 

### Expected result

It should be showing up without refresh.

### Actual result

The uploaded file didn't show up in the file manager without being refreshed.

**Comment by schnuti** [comment]
I get the same result.

Tested with version from today March 18.

**Comment by dneukirchen** [comment]
Cant confirm the issue. Latest version, chrome 64, mac. 
Tested upload of images using upload button and d&d upload.

@schnuti @proman24 please open devTools and check if any errors occur in console tab. 

Thank you.

**Comment by kasvith** [comment]
On mine i cant confirm this issue

**Comment by schnuti** [comment]
There is an error reported in the console. Windows 10 + XAMPP + FF
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]
Api.js:128:48

**Comment by laoneo** [comment]
This looks like that the ajax request failed. Can you open the url in the developer console of the ajax request which fetches the data.

**Comment by schnuti** [comment]
I should have known. There is a php-warning echoed on the server i.e. the response is corrupt.
PHP 7.2.2 in use. After setting error-level to None it works.

Warning: count(): Parameter must be an array or an object that implements Countable in D:\xampp\htdocs\j40mm0317\plugins\filesystem\local\Adapter\LocalAdapter.php on line 810

**Comment by anuragteapot** [comment]
I can't confirm this issue.

**Comment by kasvith** [comment]
@schnuti seems right, that mediaContent is not an array or countable, it needs to have something like size

**Comment by laoneo** [comment]
Can you please test #522?

**Comment by dneukirchen** [comment]
thx @laoneo
