### ISSUE TITLE
Missing triggers

### ISSUE THREAD

**Issue by dgrammatiko** [joomla-projects/media-manager-improvement#523]
### Steps to reproduce the issue

In j3 there were 2 triggers on the image upload (onBeforeContent, onAfterContent).
Can we pretty please re implement those in j4.
One of my daily used crucial plugins is rendered foo bar since these triggers were removed!

Ref:

https://github.com/joomla/joomla-cms/blob/b56a9d017b97cf00f9b229d121d2fb57d1e630fe/administrator/components/com_media/controllers/file.json.php#L118

https://github.com/joomla/joomla-cms/blob/b56a9d017b97cf00f9b229d121d2fb57d1e630fe/administrator/components/com_media/controllers/file.json.php#L222

### Expected result
Have the ability to interfere when images get uploaded

**Comment by schnuti** [comment]
#255 Proposal: include an aftersave plug in - create thumbs 
#475 Resize workflow
