### ISSUE TITLE
Actions on directories does not close itself

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#525]
### Steps to reproduce the issue
- Open NMM
- Click the button on a directory while hovering
- Click another file or directory's action button too 

### Expected result
After clicking another directory the actions should be disappear as for files we have

### Actual result
Opened action lists are still avaliable

![image](https://user-images.githubusercontent.com/13379595/38066070-f7a261dc-3323-11e8-8b42-81725eced070.png)

### System information (as much as possible)
PHP 7, Win 10, Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by laoneo** [comment]
Thanks!

**Comment by kasvith** [comment]
Closing by #534
