### ISSUE TITLE
Its possible to rename files and folders to existing files/folders

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#527]
### Steps to reproduce the issue

Rename a file to an existing file or a folder to an existing folder

### Expected result

Rename should not be possible

### Actual result

Rename is possible.

**Comment by kasvith** [comment]
hmm...this involes move in local adapter, i will take a look, at last time unit test passed

**Comment by kasvith** [comment]
As Unit tests passing need to consider more about this....pretty new to this system testing

**Comment by dneukirchen** [comment]
The failing system tests are currently skipped. You don't have to worry about them. Once we fixed the issue, I can enable them.
