### ISSUE TITLE
Use figure/figcaption 

### ISSUE THREAD

**Issue by dgrammatiko** [joomla-projects/media-manager-improvement#530]
### Steps to reproduce the issue
In J3 we had the ability to set custom title/alt for the image and then a figure was created (from an editor/xtd button). This needs to be done as well for the new media manager

context: https://github.com/joomla/joomla-cms/pull/20153#issuecomment-380843597

### Expected result
If there is a caption then the image should be in a figure tag and the caption in a figcaption tag.

### Actual result
Only img tag is produced

### Additional comments
This and the missing events in the php should be release blockers!

this probably needs some promise magic, something like select image then modal pops up asking for alt tag/caption then image tag is inserted to the editor

**Comment by schnuti** [comment]
Don't forget that you need 2 input fields. Alt **and** Caption. As I understand it, those should not be the same if e.g. a screen reader is used.
From html.com

```
    <figure>
       <img src="/path/to/flamingo.jpg" alt="flamingo">
       <figcaption>Fig.1 A pink flamingo.</figcaption>
    </figure>
```

> Except where otherwise specified, the alt attribute **must** be specified and its value must not be empty; 
> the value must be an appropriate functional replacement for the image.

[From W3C](https://www.w3.org/TR/html51/semantics-embedded-content.html#general-guidelines)

**Comment by dgrammatiko** [comment]
@schnuti true, but that is just implementation detail I guess

**Comment by schnuti** [comment]
I wanted to point out that it's not only about using the new figure/figcaption tags. As is, the inserted img tag includes alt="". This is not W3C conform and could be defined as a bug I believe.
