### ISSUE TITLE
Uploading image does not shows up in the browser

### ISSUE THREAD

**Issue by kasvith** [joomla-projects/media-manager-improvement#532]
### Steps to reproduce the issue
- Open NMM
- Upload a file

### Expected result
- Uploaded file to be shown

### Actual result
- Uploaded file is not visible, but after refresh it shows up

### System information (as much as possible)
PHP 7.1, Chrome 65 Windows (latest)

**Comment by dneukirchen** [comment]
Please check console and network in devtools. 
What type of file? Which version of media manager?

**Comment by kasvith** [comment]
There is some issue with backend, i am on it now :D 

<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\media-manager-improvement\plugins\filesystem\local\Adapter\LocalAdapter.php on line <i>810</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.2017</td><td bgcolor='#eeeeec' align='right'>394824</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\administrator\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.2022</td><td bgcolor='#eeeeec' align='right'>400264</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'C:\xampp\htdocs\media-manager-improvement\administrator\includes\app.php'</font> )</td><td title='C:\xampp\htdocs\media-manager-improvement\administrator\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>36</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.2652</td><td bgcolor='#eeeeec' align='right'>4157544</td><td bgcolor='#eeeeec'>Joomla\CMS\Application\AdministratorApplication->execute(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\administrator\includes\app.php' bgcolor='#eeeeec'>...\app.php<b>:</b>38</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.3177</td><td bgcolor='#eeeeec' align='right'>8688944</td><td bgcolor='#eeeeec'>Joomla\CMS\Application\AdministratorApplication->doExecute(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\libraries\src\Application\CMSApplication.php' bgcolor='#eeeeec'>...\CMSApplication.php<b>:</b>344</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.3243</td><td bgcolor='#eeeeec' align='right'>9036288</td><td bgcolor='#eeeeec'>Joomla\CMS\Application\AdministratorApplication->dispatch(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\libraries\src\Application\AdministratorApplication.php' bgcolor='#eeeeec'>...\AdministratorApplication.php<b>:</b>149</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.3312</td><td bgcolor='#eeeeec' align='right'>9244360</td><td bgcolor='#eeeeec'>Joomla\CMS\Component\ComponentHelper::renderComponent(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\libraries\src\Application\AdministratorApplication.php' bgcolor='#eeeeec'>...\AdministratorApplication.php<b>:</b>106</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.3340</td><td bgcolor='#eeeeec' align='right'>9281976</td><td bgcolor='#eeeeec'>Joomla\CMS\Component\ComponentHelper::dispatchComponent(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\libraries\src\Component\ComponentHelper.php' bgcolor='#eeeeec'>...\ComponentHelper.php<b>:</b>364</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.3340</td><td bgcolor='#eeeeec' align='right'>9298448</td><td bgcolor='#eeeeec'>MediaDispatcher->dispatch(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\libraries\src\Component\ComponentHelper.php' bgcolor='#eeeeec'>...\ComponentHelper.php<b>:</b>423</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.3369</td><td bgcolor='#eeeeec' align='right'>9521240</td><td bgcolor='#eeeeec'>Joomla\Component\Media\Administrator\Controller\ApiController->execute(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\libraries\src\Dispatcher\Dispatcher.php' bgcolor='#eeeeec'>...\Dispatcher.php<b>:</b>168</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.3511</td><td bgcolor='#eeeeec' align='right'>12926968</td><td bgcolor='#eeeeec'>Joomla\Component\Media\Administrator\Controller\ApiController->postFiles(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\administrator\components\com_media\Controller\ApiController.php' bgcolor='#eeeeec'>...\ApiController.php<b>:</b>70</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.3605</td><td bgcolor='#eeeeec' align='right'>14829736</td><td bgcolor='#eeeeec'>Joomla\Component\Media\Administrator\Model\ApiModel->createFile(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\administrator\components\com_media\Controller\ApiController.php' bgcolor='#eeeeec'>...\ApiController.php<b>:</b>208</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.3644</td><td bgcolor='#eeeeec' align='right'>14962680</td><td bgcolor='#eeeeec'>Joomla\Plugin\Filesystem\Local\Adapter\LocalAdapter->createFile(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\administrator\components\com_media\Model\ApiModel.php' bgcolor='#eeeeec'>...\ApiModel.php<b>:</b>271</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>0.3653</td><td bgcolor='#eeeeec' align='right'>15035200</td><td bgcolor='#eeeeec'>Joomla\Plugin\Filesystem\Local\Adapter\LocalAdapter->checkContent(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\plugins\filesystem\local\Adapter\LocalAdapter.php' bgcolor='#eeeeec'>...\LocalAdapter.php<b>:</b>228</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>0.3679</td><td bgcolor='#eeeeec' align='right'>15065808</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.count' target='_new'>count</a>
(  )</td><td title='C:\xampp\htdocs\media-manager-improvement\plugins\filesystem\local\Adapter\LocalAdapter.php' bgcolor='#eeeeec'>...\LocalAdapter.php<b>:</b>810</td></tr>
</table></font>
{"success":true,"message":null,"messages":null,"data":{"type":"file","name":"Mechanical_Eye_1920x1080.jpg","path":"local-0:\/Mechanical_Eye_1920x1080.jpg","localpath":"C:\/xampp\/htdocs\/media-manager-improvement\/images\/Mechanical_Eye_1920x1080.jpg","extension":"jpg","size":1268956,"mime_type":"image\/jpeg","width":1920,"height":1080,"create_date":"2018-04-13T12:52:04+00:00","create_date_formatted":"2018-04-13 12:52","modified_date":"2018-04-13T12:52:04+00:00","modified_date_formatted":"2018-04-13 12:52","thumb_path":"http:\/\/localhost\/media-manager-improvement\/images\/Mechanical_Eye_1920x1080.jpg","adapter":"local-0"}}

**Comment by dneukirchen** [comment]
Are you using latest dev?

i think we already fixed it in #522

**Comment by kasvith** [comment]
Wait let me do a check. seems a problem in my local repo, manually checked code in gh and it seems to be solved

Closing this
