### ISSUE TITLE
Media content view not scrollable 

### ISSUE THREAD

**Issue by anuragteapot** [joomla-projects/media-manager-improvement#537]
### Steps to reproduce the issue
1. Upload large amount of images to MM.
2. Try access all image or try to scroll.

### Expected result
Media content view scrollable. You can access all files easily .

### Actual result
Media content view not scrollable. Can't access all files.

![screenshot from 2018-04-21 14-45-39](https://user-images.githubusercontent.com/30978328/39087494-75affcee-45bf-11e8-9ef7-1ff7f82de7f6.png)

### System information (as much as possible)
Linux

**Comment by anuragteapot** [comment]
I try to do PR for this.

**Comment by kasvith** [comment]
What you mean by try accessing all files?

**Comment by anuragteapot** [comment]
> What you mean by try accessing all files?


We cant access all files because  <code> div </code> is not scrollable

**Comment by anuragteapot** [comment]
@kasvith we need a behavior like this if we have large amount of images . 

![peek 2018-04-22 00-48](https://user-images.githubusercontent.com/30978328/39087961-289dd036-45c7-11e8-9d96-d882685fd4a0.gif)

**Comment by anuragteapot** [comment]
But we can't scroll .
@ciar4n

**Comment by kasvith** [comment]
Got it, it need to be fixed

**Comment by kasvith** [comment]
I've assigned you for this.

**Comment by ciar4n** [comment]
PR created.. #541
