### ISSUE TITLE
Question - when was the last time this repo was merged to joomla-cms/4.0-dev

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-projects/media-manager-improvement#543]
Question - when was the last time this repo was merged to joomla-cms/4.0-dev

**Comment by PhilETaylor** [comment]
The following were all raised on joomla-cms/4.0-dev at 79fd94942e1758cff32da7f8f368b5f78cc75c40
google chrome


https://github.com/joomla/joomla-cms/issues/20470
https://github.com/joomla/joomla-cms/issues/20469
https://github.com/joomla/joomla-cms/issues/20468
https://github.com/joomla/joomla-cms/issues/20466
https://github.com/joomla/joomla-cms/issues/20465
https://github.com/joomla/joomla-cms/issues/20464
https://github.com/joomla/joomla-cms/issues/20463
https://github.com/joomla/joomla-cms/issues/20462

**Comment by laoneo** [comment]
Guess we can close this issue as the reports have been invalid because of an outdated installation?

**Comment by brianteeman** [comment]
It does still need updating

**Comment by laoneo** [comment]
I do that on a regular basis. No need to have an issue open for that.

**Comment by PhilETaylor** [comment]
But yet no one has answered my question. 

When was the last time? 

Because this repo was not in sync (and cause I was 90% being a dad and distracted) I wasted an hour and reported many issues that were already resolved in 4.0-dev 

——
Sent from my iPhone - sorry - if needed I’ll send longer email from my desk later.
——

**Comment by laoneo** [comment]
I did the last sync after #526 was merged this must be somewhere around beginning of April.
