### ISSUE TITLE
MM broken after update with the package from 26 june

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/media-manager-improvement#566]
### Steps to reproduce the issue
MM do not start. Message see image.

![class-not-found](https://user-images.githubusercontent.com/956537/41973658-e94e990a-7a15-11e8-904b-df389fd6cd88.png)

### Additional comments
Autoload was probably changed. My testcode had the same. Eventually I resolved my problem but that code is using standard folders. I have no idea for MM.

**Comment by dneukirchen** [comment]
Should be fixed with the next upstream merge, see https://github.com/joomla/joomla-cms/issues/20823

**Comment by laoneo** [comment]
Upstream is merged https://github.com/joomla-projects/media-manager-improvement/commit/bb11af2ab35390292e6813d0cada72f66e46b68c.
