### ISSUE TITLE
[API] Handle invalid path requests

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#82]
### Steps to reproduce the issue
Make a get request with an invalid path 

```GET /administrator/index.php?option=com_media&format=json&task=api.files&path=some-invalid---or-not-existing-path```

### Expected result
Server responds with an 404 error.

### Actual result
Server responds with an 200 error and empty data set

**Comment by laoneo** [comment]
Closing as we have a pr #96.
