### ISSUE TITLE
Adjust names of newly created folders

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#93]
Follow up todo from https://github.com/joomla-projects/media-manager-improvement/pull/90

currently all whitespaces are stripped, perhaps it is better to replace them with '-'

**Comment by laoneo** [comment]
Is this an issue on the client side or api?

**Comment by dneukirchen** [comment]
Nope, its handled by the server (JFolder::create()). We have to manually modify it before sending the name to JFolder::create().

**Comment by laoneo** [comment]
Can we close this in favor of #107?
