### ISSUE TITLE
Implement transition effects for the modal

### ISSUE THREAD

**Issue by dneukirchen** [joomla-projects/media-manager-improvement#95]
Follow up todo from https://github.com/joomla-projects/media-manager-improvement/pull/90

**Comment by dgrammatiko** [comment]
I can help here, as I already messed with this for my custom elements quest

**Comment by dneukirchen** [comment]
Would be great. Go for it. 
With vue transitions this should be just  ```<transition name="fade">...</transition>``` and the corresponding css classes. 
https://vuejs.org/v2/guide/transitions.html
